package com.example.creditcard.ui.wallet

import com.example.creditcard.R

internal object WalletLogoCatalogData {
    val entries by lazy { buildList {
        addAll(part0())
        addAll(part1())
        addAll(part2())
        addAll(part3())
        addAll(part4())
        addAll(part5())
        addAll(part6())
    } }
    private fun part0() = listOf(
        WalletIssuerLogo("abchina", "中国农业银行", R.drawable.wallet_issuer_abchina, R.drawable.wallet_issuer_abchina_card, 0xFF23745F, listOf("Agricultural Bank of China", "abc", "agriculturalbank", "中国农业银行", "农业银行", "农行", "農業銀行")),
        WalletIssuerLogo("abnamro", "荷兰银行", R.drawable.wallet_issuer_abnamro, R.drawable.wallet_issuer_abnamro_card, 0xFF246977, listOf("ABN AMRO", "荷兰银行")),
        WalletIssuerLogo("amex", "American Express", R.drawable.wallet_issuer_amex, R.drawable.wallet_issuer_amex_card, 0xFF356A88, listOf("AMEX", "American Express", "American Express National Bank", "americanexpress", "amex", "美国运通", "美國運通")),
        WalletIssuerLogo("anz", "澳新银行", R.drawable.wallet_issuer_anz, R.drawable.wallet_issuer_anz_card, 0xFF315D52, listOf("ANZ", "ANZ Banking Group", "Australia & New Zealand Banking Group", "澳新银行")),
        WalletIssuerLogo("bangkokbank", "盘谷银行", R.drawable.wallet_issuer_bangkokbank, R.drawable.wallet_issuer_bangkokbank_card, 0xFF244B6B, listOf("盘谷银行")),
        WalletIssuerLogo("bankcomm", "交通银行", R.drawable.wallet_issuer_bankcomm, R.drawable.wallet_issuer_bankcomm_card, 0xFF3B70AA, listOf("bankofcommunications", "bcm", "bocom", "交通銀行", "交通银行")),
        WalletIssuerLogo("bankcz", "沧州银行", R.drawable.wallet_issuer_bankcz, R.drawable.wallet_issuer_bankcz_card, 0xFF246977, listOf("沧州银行")),
        WalletIssuerLogo("bankgy", "贵阳银行", R.drawable.wallet_issuer_bankgy, R.drawable.wallet_issuer_bankgy_card, 0xFF79412E, listOf("贵阳银行")),
        WalletIssuerLogo("bankofamerica", "美国银行", R.drawable.wallet_issuer_bankofamerica, R.drawable.wallet_issuer_bankofamerica_card, 0xFF385789, listOf("Bank of America", "BofA", "bankofamerica", "boa", "bofa", "美国银行", "美國銀行")),
        WalletIssuerLogo("bankofas", "鞍山银行", R.drawable.wallet_issuer_bankofas, R.drawable.wallet_issuer_bankofas_card, 0xFF244B6B, listOf("鞍山银行")),
        WalletIssuerLogo("bankofbbg", "广西北部湾银行", R.drawable.wallet_issuer_bankofbbg, R.drawable.wallet_issuer_bankofbbg_card, 0xFF79412E, listOf("广西北部湾银行")),
        WalletIssuerLogo("bankofbeijing", "北京银行", R.drawable.wallet_issuer_bankofbeijing, R.drawable.wallet_issuer_bankofbeijing_card, 0xFF244B6B, listOf("BOB", "Bank of Beijing", "北京银行")),
        WalletIssuerLogo("bankofdl", "大连银行", R.drawable.wallet_issuer_bankofdl, R.drawable.wallet_issuer_bankofdl_card, 0xFF6F3859, listOf("大连银行")),
        WalletIssuerLogo("bankoffs", "抚顺银行", R.drawable.wallet_issuer_bankoffs, R.drawable.wallet_issuer_bankoffs_card, 0xFF394B80, listOf("抚顺银行")),
        WalletIssuerLogo("bankofhld", "葫芦岛银行", R.drawable.wallet_issuer_bankofhld, R.drawable.wallet_issuer_bankofhld_card, 0xFF244B6B, listOf("葫芦岛银行")),
        WalletIssuerLogo("bankofnx", "宁夏银行", R.drawable.wallet_issuer_bankofnx, R.drawable.wallet_issuer_bankofnx_card, 0xFF394B80, listOf("宁夏银行")),
        WalletIssuerLogo("bankofpj", "盘锦银行", R.drawable.wallet_issuer_bankofpj, R.drawable.wallet_issuer_bankofpj_card, 0xFF394B80, listOf("盘锦银行")),
        WalletIssuerLogo("bankofrizhao", "日照银行", R.drawable.wallet_issuer_bankofrizhao, R.drawable.wallet_issuer_bankofrizhao_card, 0xFF315D52, listOf("日照银行")),
        WalletIssuerLogo("bankoftianjin", "天津银行", R.drawable.wallet_issuer_bankoftianjin, R.drawable.wallet_issuer_bankoftianjin_card, 0xFF246977, listOf("Bank of Tianjin", "天津银行")),
        WalletIssuerLogo("bankoftieling", "铁岭银行", R.drawable.wallet_issuer_bankoftieling, R.drawable.wallet_issuer_bankoftieling_card, 0xFF394B80, listOf("铁岭银行")),
        WalletIssuerLogo("bankofyk", "营口银行", R.drawable.wallet_issuer_bankofyk, R.drawable.wallet_issuer_bankofyk_card, 0xFF244B6B, listOf("营口银行")),
        WalletIssuerLogo("bankqh", "青海银行", R.drawable.wallet_issuer_bankqh, R.drawable.wallet_issuer_bankqh_card, 0xFF315D52, listOf("青海银行")),
        WalletIssuerLogo("bankwf", "潍坊银行", R.drawable.wallet_issuer_bankwf, R.drawable.wallet_issuer_bankwf_card, 0xFF394B80, listOf("潍坊银行")),
        WalletIssuerLogo("bankyellowriver", "黄河农商", R.drawable.wallet_issuer_bankyellowriver, R.drawable.wallet_issuer_bankyellowriver_card, 0xFF244B6B, listOf("黄河农商", "黄河农商银行", "黄河农村商业银行")),
        WalletIssuerLogo("barclays", "巴克莱银行", R.drawable.wallet_issuer_barclays, R.drawable.wallet_issuer_barclays_card, 0xFF315D52, listOf("Barclays", "Barclays Bank", "巴克莱银行")),
        WalletIssuerLogo("bcm", "澳门商业银行", R.drawable.wallet_issuer_bcm, R.drawable.wallet_issuer_bcm_card, 0xFF79412E, listOf("澳门商业银行")),
        WalletIssuerLogo("bd-bank", "保定银行", R.drawable.wallet_issuer_bd_bank, R.drawable.wallet_issuer_bd_bank_card, 0xFF246977, listOf("保定银行")),
        WalletIssuerLogo("bea", "东亚银行", R.drawable.wallet_issuer_bea, R.drawable.wallet_issuer_bea_card, 0xFF246977, listOf("Bank of East Asia", "东亚银行", "東亞銀行")),
        WalletIssuerLogo("bgzchina", "贵州银行", R.drawable.wallet_issuer_bgzchina, R.drawable.wallet_issuer_bgzchina_card, 0xFF79412E, listOf("贵州银行")),
        WalletIssuerLogo("bjrcb", "北京农商银行", R.drawable.wallet_issuer_bjrcb, R.drawable.wallet_issuer_bjrcb_card, 0xFF6F3859, listOf("北京农商银行")),
        WalletIssuerLogo("bmo", "蒙特利尔银行", R.drawable.wallet_issuer_bmo, R.drawable.wallet_issuer_bmo_card, 0xFF315D52, listOf("BMO", "Bank of Montreal", "蒙特利尔银行")),
        WalletIssuerLogo("bnp", "法国巴黎银行", R.drawable.wallet_issuer_bnp, R.drawable.wallet_issuer_bnp_card, 0xFF246977, listOf("BNP Paribas", "法国巴黎银行")),
        WalletIssuerLogo("boc", "中国银行", R.drawable.wallet_issuer_boc, R.drawable.wallet_issuer_boc_card, 0xFF394453, listOf("Bank of China", "bankofchina", "boc", "bochk", "中国银行", "中國銀行", "中銀香港", "中银香港")),
        WalletIssuerLogo("bocd", "成都银行", R.drawable.wallet_issuer_bocd, R.drawable.wallet_issuer_bocd_card, 0xFF315D52, listOf("Bank of Chengdu", "成都银行")),
        WalletIssuerLogo("bohuihe", "汇和银行", R.drawable.wallet_issuer_bohuihe, R.drawable.wallet_issuer_bohuihe_card, 0xFF244B6B, listOf("汇和银行")),
        WalletIssuerLogo("bolz", "柳州银行", R.drawable.wallet_issuer_bolz, R.drawable.wallet_issuer_bolz_card, 0xFF244B6B, listOf("柳州银行")),
        WalletIssuerLogo("bosc", "上海银行", R.drawable.wallet_issuer_bosc, R.drawable.wallet_issuer_bosc_card, 0xFF6F3859, listOf("Bank of Shanghai", "上海银行")),
        WalletIssuerLogo("boy", "横滨银行", R.drawable.wallet_issuer_boy, R.drawable.wallet_issuer_boy_card, 0xFF394B80, listOf("横滨银行")),
        WalletIssuerLogo("bunq", "bunq", R.drawable.wallet_issuer_bunq, R.drawable.wallet_issuer_bunq_card, 0xFF6F3859, listOf("bunq")),
        WalletIssuerLogo("cacib", "Crédit Agricole CIB", R.drawable.wallet_issuer_cacib, R.drawable.wallet_issuer_cacib_card, 0xFF79412E, listOf("Credit Agricole", "Crédit Agricole", "Crédit Agricole CIB", "法国农业信贷银行")),
        WalletIssuerLogo("cathaybk", "国泰世华银行", R.drawable.wallet_issuer_cathaybk, R.drawable.wallet_issuer_cathaybk_card, 0xFF246977, listOf("国泰世华银行")),
        WalletIssuerLogo("cbhb", "渤海银行", R.drawable.wallet_issuer_cbhb, R.drawable.wallet_issuer_cbhb_card, 0xFF394B80, listOf("China Bohai Bank", "渤海银行")),
        WalletIssuerLogo("ccabchina", "长安银行", R.drawable.wallet_issuer_ccabchina, R.drawable.wallet_issuer_ccabchina_card, 0xFF6F3859, listOf("Bank of Changan", "长安银行")),
        WalletIssuerLogo("ccb", "中国建设银行", R.drawable.wallet_issuer_ccb, R.drawable.wallet_issuer_ccb_card, 0xFF315E98, listOf("China Construction Bank", "ccb", "chinaconstructionbank", "中国建设银行", "建行", "建設銀行", "建设银行")),
        WalletIssuerLogo("ccqtgb", "重庆三峡银行", R.drawable.wallet_issuer_ccqtgb, R.drawable.wallet_issuer_ccqtgb_card, 0xFF244B6B, listOf("重庆三峡银行")),
        WalletIssuerLogo("cdb", "国家开发银行", R.drawable.wallet_issuer_cdb, R.drawable.wallet_issuer_cdb_card, 0xFF79412E, listOf("国家开发银行")),
        WalletIssuerLogo("cebbank", "中国光大银行", R.drawable.wallet_issuer_cebbank, R.drawable.wallet_issuer_cebbank_card, 0xFF69517D, listOf("ceb", "chinaeverbright", "中国光大银行", "光大銀行", "光大银行")),
        WalletIssuerLogo("cgbchina", "广发银行", R.drawable.wallet_issuer_cgbchina, R.drawable.wallet_issuer_cgbchina_card, 0xFF923642, listOf("cgb", "chinaguangfa", "广发银行", "廣發銀行")),
        WalletIssuerLogo("chase", "摩根大通银行", R.drawable.wallet_issuer_chase, R.drawable.wallet_issuer_chase_card, 0xFF30598D, listOf("Chase", "J.P. Morgan Chase", "JPMorgan Chase", "chase", "大通銀行", "大通银行", "摩根大通银行")),
        WalletIssuerLogo("chengdebank", "承德银行", R.drawable.wallet_issuer_chengdebank, R.drawable.wallet_issuer_chengdebank_card, 0xFF315D52, listOf("承德银行")),
        WalletIssuerLogo("cib", "兴业银行", R.drawable.wallet_issuer_cib, R.drawable.wallet_issuer_cib_card, 0xFF374D83, listOf("cib", "industrialbank", "兴业银行", "興業銀行")),
        WalletIssuerLogo("citibank", "花旗银行", R.drawable.wallet_issuer_citibank, R.drawable.wallet_issuer_citibank_card, 0xFF345C8D, listOf("Citi", "Citibank", "citi", "citibank", "花旗", "花旗银行")),
        WalletIssuerLogo("citicbank", "中信银行", R.drawable.wallet_issuer_citicbank, R.drawable.wallet_issuer_citicbank_card, 0xFF923A47, listOf("citic", "中信銀行", "中信银行")),
        WalletIssuerLogo("cjccb", "江苏长江商业银行", R.drawable.wallet_issuer_cjccb, R.drawable.wallet_issuer_cjccb_card, 0xFF79412E, listOf("江苏长江商业银行")),
        WalletIssuerLogo("cmbc", "中国民生银行", R.drawable.wallet_issuer_cmbc, R.drawable.wallet_issuer_cmbc_card, 0xFF357163, listOf("chinaminsheng", "cmbc", "中国民生银行", "民生銀行", "民生银行")),
        WalletIssuerLogo("cmbchina", "招商银行", R.drawable.wallet_issuer_cmbchina, R.drawable.wallet_issuer_cmbchina_card, 0xFFA93643, listOf("China Merchants Bank", "chinamerchantsbank", "cmb", "招商銀行", "招商银行", "招行")),
        WalletIssuerLogo("cmbcn", "华商银行", R.drawable.wallet_issuer_cmbcn, R.drawable.wallet_issuer_cmbcn_card, 0xFF79412E, listOf("华商银行")),
        WalletIssuerLogo("cn_00128270f10e", "浦发硅谷银行", R.drawable.wallet_issuer_cn_00128270f10e, R.drawable.wallet_issuer_cn_00128270f10e_card, 0xFF394B80, listOf("浦发硅谷银行")),
        WalletIssuerLogo("cn_023fab480bec", "张家口银行", R.drawable.wallet_issuer_cn_023fab480bec, R.drawable.wallet_issuer_cn_023fab480bec_card, 0xFF79412E, listOf("张家口银行")),
        WalletIssuerLogo("cn_06e81ea7ab55", "北京顺义银座村镇银行", R.drawable.wallet_issuer_cn_06e81ea7ab55, R.drawable.wallet_issuer_cn_06e81ea7ab55_card, 0xFF244B6B, listOf("北京顺义银座村镇银行")),
    )
    private fun part1() = listOf(
        WalletIssuerLogo("cn_072b7c76dd03", "鹤壁银行", R.drawable.wallet_issuer_cn_072b7c76dd03, R.drawable.wallet_issuer_cn_072b7c76dd03_card, 0xFF79412E, listOf("鹤壁银行")),
        WalletIssuerLogo("cn_09371ad2d6c4", "西藏银行", R.drawable.wallet_issuer_cn_09371ad2d6c4, R.drawable.wallet_issuer_cn_09371ad2d6c4_card, 0xFF246977, listOf("西藏银行")),
        WalletIssuerLogo("cn_0b0e76ff3e7c", "台湾玉山银行", R.drawable.wallet_issuer_cn_0b0e76ff3e7c, R.drawable.wallet_issuer_cn_0b0e76ff3e7c_card, 0xFF79412E, listOf("台湾玉山银行")),
        WalletIssuerLogo("cn_0b28f6bfe074", "路程农村合作银行", R.drawable.wallet_issuer_cn_0b28f6bfe074, R.drawable.wallet_issuer_cn_0b28f6bfe074_card, 0xFF315D52, listOf("路程农村合作银行")),
        WalletIssuerLogo("cn_13c708b4ed82", "焦作市商业银行", R.drawable.wallet_issuer_cn_13c708b4ed82, R.drawable.wallet_issuer_cn_13c708b4ed82_card, 0xFF79412E, listOf("焦作市商业银行")),
        WalletIssuerLogo("cn_18d4358ba8c5", "江苏兴化农商", R.drawable.wallet_issuer_cn_18d4358ba8c5, R.drawable.wallet_issuer_cn_18d4358ba8c5_card, 0xFF79412E, listOf("江苏兴化农商", "江苏兴化农商银行", "江苏兴化农村商业银行")),
        WalletIssuerLogo("cn_253c9ae64bcc", "法国汇理银行", R.drawable.wallet_issuer_cn_253c9ae64bcc, R.drawable.wallet_issuer_cn_253c9ae64bcc_card, 0xFF246977, listOf("法国汇理银行")),
        WalletIssuerLogo("cn_25663810b047", "雅安市商业银行", R.drawable.wallet_issuer_cn_25663810b047, R.drawable.wallet_issuer_cn_25663810b047_card, 0xFF6F3859, listOf("雅安市商业银行")),
        WalletIssuerLogo("cn_2dc42d631407", "南通农商银行", R.drawable.wallet_issuer_cn_2dc42d631407, R.drawable.wallet_issuer_cn_2dc42d631407_card, 0xFF315D52, listOf("南通农商银行")),
        WalletIssuerLogo("cn_2e71425803cd", "萧山农村合作银行", R.drawable.wallet_issuer_cn_2e71425803cd, R.drawable.wallet_issuer_cn_2e71425803cd_card, 0xFF315D52, listOf("萧山农村合作银行")),
        WalletIssuerLogo("cn_30d405b9d231", "韩国外换银行", R.drawable.wallet_issuer_cn_30d405b9d231, R.drawable.wallet_issuer_cn_30d405b9d231_card, 0xFF315D52, listOf("韩国外换银行")),
        WalletIssuerLogo("cn_370deb434461", "辽阳银行", R.drawable.wallet_issuer_cn_370deb434461, R.drawable.wallet_issuer_cn_370deb434461_card, 0xFF394B80, listOf("辽阳银行")),
        WalletIssuerLogo("cn_3782697fe73d", "泰州农村商业银行", R.drawable.wallet_issuer_cn_3782697fe73d, R.drawable.wallet_issuer_cn_3782697fe73d_card, 0xFF246977, listOf("泰州农商", "泰州农商银行", "泰州农村商业银行")),
        WalletIssuerLogo("cn_3afe256d07c4", "瑞典银行", R.drawable.wallet_issuer_cn_3afe256d07c4, R.drawable.wallet_issuer_cn_3afe256d07c4_card, 0xFF244B6B, listOf("瑞典银行")),
        WalletIssuerLogo("cn_3f009ff4176b", "池州九华农商", R.drawable.wallet_issuer_cn_3f009ff4176b, R.drawable.wallet_issuer_cn_3f009ff4176b_card, 0xFF244B6B, listOf("池州九华农商", "池州九华农商银行", "池州九华农村商业银行")),
        WalletIssuerLogo("cn_3f4932c6c3ff", "湖州市商业银行", R.drawable.wallet_issuer_cn_3f4932c6c3ff, R.drawable.wallet_issuer_cn_3f4932c6c3ff_card, 0xFF6F3859, listOf("湖州市商业银行")),
        WalletIssuerLogo("cn_405c21dcbde2", "摩根士丹利国际银行", R.drawable.wallet_issuer_cn_405c21dcbde2, R.drawable.wallet_issuer_cn_405c21dcbde2_card, 0xFF79412E, listOf("摩根士丹利国际银行")),
        WalletIssuerLogo("cn_42b69ae7787b", "新会农商", R.drawable.wallet_issuer_cn_42b69ae7787b, R.drawable.wallet_issuer_cn_42b69ae7787b_card, 0xFF315D52, listOf("新会农商", "新会农商银行", "新会农村商业银行")),
        WalletIssuerLogo("cn_505336886585", "洪都农商", R.drawable.wallet_issuer_cn_505336886585, R.drawable.wallet_issuer_cn_505336886585_card, 0xFF315D52, listOf("洪都农商", "洪都农商银行", "洪都农村商业银行")),
        WalletIssuerLogo("cn_5385e1fa7932", "鄞州银行", R.drawable.wallet_issuer_cn_5385e1fa7932, R.drawable.wallet_issuer_cn_5385e1fa7932_card, 0xFF244B6B, listOf("鄞州银行")),
        WalletIssuerLogo("cn_551e5f0092ec", "德累斯顿银行", R.drawable.wallet_issuer_cn_551e5f0092ec, R.drawable.wallet_issuer_cn_551e5f0092ec_card, 0xFF244B6B, listOf("德累斯顿银行")),
        WalletIssuerLogo("cn_59919b79b5fb", "法国里昂信贷银行", R.drawable.wallet_issuer_cn_59919b79b5fb, R.drawable.wallet_issuer_cn_59919b79b5fb_card, 0xFF394B80, listOf("法国里昂信贷银行")),
        WalletIssuerLogo("cn_5bd14b969bb7", "张家港农商", R.drawable.wallet_issuer_cn_5bd14b969bb7, R.drawable.wallet_issuer_cn_5bd14b969bb7_card, 0xFF244B6B, listOf("张家港农商", "张家港农商银行", "张家港农村商业银行")),
        WalletIssuerLogo("cn_5c75aa68746a", "景德镇商业银行", R.drawable.wallet_issuer_cn_5c75aa68746a, R.drawable.wallet_issuer_cn_5c75aa68746a_card, 0xFF315D52, listOf("景德镇商业银行")),
        WalletIssuerLogo("cn_5cc85c2ca746", "太仓农商", R.drawable.wallet_issuer_cn_5cc85c2ca746, R.drawable.wallet_issuer_cn_5cc85c2ca746_card, 0xFF246977, listOf("太仓农商", "太仓农商银行", "太仓农村商业银行")),
        WalletIssuerLogo("cn_5e9d1ca03dad", "沧州融信农商", R.drawable.wallet_issuer_cn_5e9d1ca03dad, R.drawable.wallet_issuer_cn_5e9d1ca03dad_card, 0xFF79412E, listOf("沧州融信农商", "沧州融信农商银行", "沧州融信农村商业银行")),
        WalletIssuerLogo("cn_60409c5b4038", "陆丰农村信用社", R.drawable.wallet_issuer_cn_60409c5b4038, R.drawable.wallet_issuer_cn_60409c5b4038_card, 0xFF246977, listOf("陆丰农村信用社")),
        WalletIssuerLogo("cn_638c513b7a9c", "新乡银行", R.drawable.wallet_issuer_cn_638c513b7a9c, R.drawable.wallet_issuer_cn_638c513b7a9c_card, 0xFF315D52, listOf("新乡银行")),
        WalletIssuerLogo("cn_638e4d6c6d51", "芜湖扬子农商", R.drawable.wallet_issuer_cn_638e4d6c6d51, R.drawable.wallet_issuer_cn_638e4d6c6d51_card, 0xFF6F3859, listOf("芜湖扬子农商", "芜湖扬子农商银行", "芜湖扬子农村商业银行")),
        WalletIssuerLogo("cn_63c428ac6485", "邢台银行", R.drawable.wallet_issuer_cn_63c428ac6485, R.drawable.wallet_issuer_cn_63c428ac6485_card, 0xFF246977, listOf("邢台银行")),
        WalletIssuerLogo("cn_6dc7aa5f5663", "台州农村合作银行", R.drawable.wallet_issuer_cn_6dc7aa5f5663, R.drawable.wallet_issuer_cn_6dc7aa5f5663_card, 0xFF6F3859, listOf("台州农村合作银行")),
        WalletIssuerLogo("cn_6fad59ae3f0a", "中华开发工业银行", R.drawable.wallet_issuer_cn_6fad59ae3f0a, R.drawable.wallet_issuer_cn_6fad59ae3f0a_card, 0xFF79412E, listOf("中华开发工业银行")),
        WalletIssuerLogo("cn_718f5809cc87", "湖滨农商", R.drawable.wallet_issuer_cn_718f5809cc87, R.drawable.wallet_issuer_cn_718f5809cc87_card, 0xFF244B6B, listOf("湖滨农商", "湖滨农商银行", "湖滨农村商业银行")),
        WalletIssuerLogo("cn_7a17ea7550e6", "大同银行", R.drawable.wallet_issuer_cn_7a17ea7550e6, R.drawable.wallet_issuer_cn_7a17ea7550e6_card, 0xFF394B80, listOf("大同银行")),
        WalletIssuerLogo("cn_7b047165711c", "深圳农商", R.drawable.wallet_issuer_cn_7b047165711c, R.drawable.wallet_issuer_cn_7b047165711c_card, 0xFF246977, listOf("深圳农商", "深圳农商银行", "深圳农村商业银行")),
        WalletIssuerLogo("cn_7c8811fb22c8", "中国银行业监督", R.drawable.wallet_issuer_cn_7c8811fb22c8, R.drawable.wallet_issuer_cn_7c8811fb22c8_card, 0xFF6F3859, listOf("中国银行业监督")),
        WalletIssuerLogo("cn_7ea02e13b47b", "长春农商", R.drawable.wallet_issuer_cn_7ea02e13b47b, R.drawable.wallet_issuer_cn_7ea02e13b47b_card, 0xFF315D52, listOf("长春农商", "长春农商银行", "长春农村商业银行")),
        WalletIssuerLogo("cn_7fec0344aab1", "凉山商业银行", R.drawable.wallet_issuer_cn_7fec0344aab1, R.drawable.wallet_issuer_cn_7fec0344aab1_card, 0xFF6F3859, listOf("凉山商业银行")),
        WalletIssuerLogo("cn_80558f8f6dba", "威海商业银行", R.drawable.wallet_issuer_cn_80558f8f6dba, R.drawable.wallet_issuer_cn_80558f8f6dba_card, 0xFF315D52, listOf("威海商业银行")),
        WalletIssuerLogo("cn_82ee6c840b13", "湖南华容农商", R.drawable.wallet_issuer_cn_82ee6c840b13, R.drawable.wallet_issuer_cn_82ee6c840b13_card, 0xFF394B80, listOf("湖南华容农商", "湖南华容农商银行", "湖南华容农村商业银行")),
        WalletIssuerLogo("cn_833a9902d983", "周口银行", R.drawable.wallet_issuer_cn_833a9902d983, R.drawable.wallet_issuer_cn_833a9902d983_card, 0xFF6F3859, listOf("周口银行")),
        WalletIssuerLogo("cn_8634bf23b2c7", "云南红塔银行", R.drawable.wallet_issuer_cn_8634bf23b2c7, R.drawable.wallet_issuer_cn_8634bf23b2c7_card, 0xFF6F3859, listOf("云南红塔银行")),
        WalletIssuerLogo("cn_88952e5b892f", "苏格兰皇家银行", R.drawable.wallet_issuer_cn_88952e5b892f, R.drawable.wallet_issuer_cn_88952e5b892f_card, 0xFF394B80, listOf("苏格兰皇家银行")),
        WalletIssuerLogo("cn_895bcf7a4f76", "商丘市商业银行", R.drawable.wallet_issuer_cn_895bcf7a4f76, R.drawable.wallet_issuer_cn_895bcf7a4f76_card, 0xFF394B80, listOf("商丘市商业银行")),
        WalletIssuerLogo("cn_8dd89a5f87a6", "伊川农商", R.drawable.wallet_issuer_cn_8dd89a5f87a6, R.drawable.wallet_issuer_cn_8dd89a5f87a6_card, 0xFF315D52, listOf("伊川农商", "伊川农商银行", "伊川农村商业银行")),
        WalletIssuerLogo("cn_9062097cf3ec", "开封市商业银行", R.drawable.wallet_issuer_cn_9062097cf3ec, R.drawable.wallet_issuer_cn_9062097cf3ec_card, 0xFF394B80, listOf("开封市商业银行")),
        WalletIssuerLogo("cn_93d9b6515112", "江门融合农商", R.drawable.wallet_issuer_cn_93d9b6515112, R.drawable.wallet_issuer_cn_93d9b6515112_card, 0xFF244B6B, listOf("江门融合农商", "江门融合农商银行", "江门融合农村商业银行")),
        WalletIssuerLogo("cn_96d8d823ccd9", "台湾中小企业银行", R.drawable.wallet_issuer_cn_96d8d823ccd9, R.drawable.wallet_issuer_cn_96d8d823ccd9_card, 0xFF315D52, listOf("台湾中小企业银行")),
        WalletIssuerLogo("cn_97401bb60482", "紫金农商", R.drawable.wallet_issuer_cn_97401bb60482, R.drawable.wallet_issuer_cn_97401bb60482_card, 0xFF246977, listOf("紫金农商", "紫金农商银行", "紫金农村商业银行")),
        WalletIssuerLogo("cn_9cab9ee7aaf4", "安阳银行", R.drawable.wallet_issuer_cn_9cab9ee7aaf4, R.drawable.wallet_issuer_cn_9cab9ee7aaf4_card, 0xFF6F3859, listOf("安阳银行")),
        WalletIssuerLogo("cn_9d7dca5dd6ce", "信阳银行", R.drawable.wallet_issuer_cn_9d7dca5dd6ce, R.drawable.wallet_issuer_cn_9d7dca5dd6ce_card, 0xFF79412E, listOf("信阳银行")),
        WalletIssuerLogo("cn_a147b0bd0a33", "平顶山银行", R.drawable.wallet_issuer_cn_a147b0bd0a33, R.drawable.wallet_issuer_cn_a147b0bd0a33_card, 0xFF6F3859, listOf("平顶山银行")),
        WalletIssuerLogo("cn_a542e0f25594", "菲律宾首都银行", R.drawable.wallet_issuer_cn_a542e0f25594, R.drawable.wallet_issuer_cn_a542e0f25594_card, 0xFF246977, listOf("菲律宾首都银行")),
        WalletIssuerLogo("cn_a82aa0b5634d", "宜宾商业银行", R.drawable.wallet_issuer_cn_a82aa0b5634d, R.drawable.wallet_issuer_cn_a82aa0b5634d_card, 0xFF244B6B, listOf("宜宾商业银行")),
        WalletIssuerLogo("cn_adcab5c89892", "江苏如皋农商", R.drawable.wallet_issuer_cn_adcab5c89892, R.drawable.wallet_issuer_cn_adcab5c89892_card, 0xFF244B6B, listOf("江苏如皋农商", "江苏如皋农商银行", "江苏如皋农村商业银行")),
        WalletIssuerLogo("cn_ba94b79359e9", "江苏扬州农商", R.drawable.wallet_issuer_cn_ba94b79359e9, R.drawable.wallet_issuer_cn_ba94b79359e9_card, 0xFF244B6B, listOf("江苏扬州农商", "江苏扬州农商银行", "江苏扬州农村商业银行")),
        WalletIssuerLogo("cn_bfbaad7b803f", "栾川农商", R.drawable.wallet_issuer_cn_bfbaad7b803f, R.drawable.wallet_issuer_cn_bfbaad7b803f_card, 0xFF246977, listOf("栾川农商", "栾川农商银行", "栾川农村商业银行")),
        WalletIssuerLogo("cn_c2d3f86a7988", "三菱UFJ银行（日联）", R.drawable.wallet_issuer_cn_c2d3f86a7988, R.drawable.wallet_issuer_cn_c2d3f86a7988_card, 0xFF394B80, listOf("三菱UFJ银行（日联）")),
        WalletIssuerLogo("cn_c7ab0b0172a5", "北欧斯安银行", R.drawable.wallet_issuer_cn_c7ab0b0172a5, R.drawable.wallet_issuer_cn_c7ab0b0172a5_card, 0xFF79412E, listOf("北欧斯安银行")),
        WalletIssuerLogo("cn_cb46bbb9afeb", "高明农商", R.drawable.wallet_issuer_cn_cb46bbb9afeb, R.drawable.wallet_issuer_cn_cb46bbb9afeb_card, 0xFF246977, listOf("高明农商", "高明农商银行", "高明农村商业银行")),
    )
    private fun part2() = listOf(
        WalletIssuerLogo("cn_cb94de0f3c21", "大庆市商业银行", R.drawable.wallet_issuer_cn_cb94de0f3c21, R.drawable.wallet_issuer_cn_cb94de0f3c21_card, 0xFF244B6B, listOf("大庆市商业银行")),
        WalletIssuerLogo("cn_cbc95fdba110", "阳泉市商业银行", R.drawable.wallet_issuer_cn_cbc95fdba110, R.drawable.wallet_issuer_cn_cbc95fdba110_card, 0xFF244B6B, listOf("阳泉市商业银行")),
        WalletIssuerLogo("cn_cc44a3e3c534", "台湾银行", R.drawable.wallet_issuer_cn_cc44a3e3c534, R.drawable.wallet_issuer_cn_cc44a3e3c534_card, 0xFF244B6B, listOf("台湾银行")),
        WalletIssuerLogo("cn_d2782514a1f3", "安顺市商业银行", R.drawable.wallet_issuer_cn_d2782514a1f3, R.drawable.wallet_issuer_cn_d2782514a1f3_card, 0xFF394B80, listOf("安顺市商业银行")),
        WalletIssuerLogo("cn_d2c84af17648", "比利时银行", R.drawable.wallet_issuer_cn_d2c84af17648, R.drawable.wallet_issuer_cn_d2c84af17648_card, 0xFF246977, listOf("比利时银行")),
        WalletIssuerLogo("cn_d3a381d4f562", "广东揭阳农商", R.drawable.wallet_issuer_cn_d3a381d4f562, R.drawable.wallet_issuer_cn_d3a381d4f562_card, 0xFF394B80, listOf("广东揭阳农商", "广东揭阳农商银行", "广东揭阳农村商业银行")),
        WalletIssuerLogo("cn_db3aa82a331e", "包商银行", R.drawable.wallet_issuer_cn_db3aa82a331e, R.drawable.wallet_issuer_cn_db3aa82a331e_card, 0xFF244B6B, listOf("包商银行")),
        WalletIssuerLogo("cn_deb0f264dc85", "吴江农商", R.drawable.wallet_issuer_cn_deb0f264dc85, R.drawable.wallet_issuer_cn_deb0f264dc85_card, 0xFF244B6B, listOf("吴江农商", "吴江农商银行", "吴江农村商业银行")),
        WalletIssuerLogo("cn_e82d7b98c10b", "韩国友利银行", R.drawable.wallet_issuer_cn_e82d7b98c10b, R.drawable.wallet_issuer_cn_e82d7b98c10b_card, 0xFF6F3859, listOf("韩国友利银行")),
        WalletIssuerLogo("cn_e9ecd031a383", "晋城银行", R.drawable.wallet_issuer_cn_e9ecd031a383, R.drawable.wallet_issuer_cn_e9ecd031a383_card, 0xFF79412E, listOf("晋城银行")),
        WalletIssuerLogo("cn_ea01251165c8", "许昌魏都农商", R.drawable.wallet_issuer_cn_ea01251165c8, R.drawable.wallet_issuer_cn_ea01251165c8_card, 0xFF246977, listOf("许昌魏都农商", "许昌魏都农商银行", "许昌魏都农村商业银行")),
        WalletIssuerLogo("cn_ec06ece75df2", "三和银行", R.drawable.wallet_issuer_cn_ec06ece75df2, R.drawable.wallet_issuer_cn_ec06ece75df2_card, 0xFF79412E, listOf("三和银行")),
        WalletIssuerLogo("cn_f091a0ee24b4", "瑞穗实业银行", R.drawable.wallet_issuer_cn_f091a0ee24b4, R.drawable.wallet_issuer_cn_f091a0ee24b4_card, 0xFF6F3859, listOf("瑞穗实业银行")),
        WalletIssuerLogo("cn_f0d0b10ec5f5", "台湾土地银行", R.drawable.wallet_issuer_cn_f0d0b10ec5f5, R.drawable.wallet_issuer_cn_f0d0b10ec5f5_card, 0xFF394B80, listOf("台湾土地银行")),
        WalletIssuerLogo("cn_f1c55c4290dd", "波士顿银行", R.drawable.wallet_issuer_cn_f1c55c4290dd, R.drawable.wallet_issuer_cn_f1c55c4290dd_card, 0xFF246977, listOf("波士顿银行")),
        WalletIssuerLogo("cn_f5fee79339ce", "许昌银行", R.drawable.wallet_issuer_cn_f5fee79339ce, R.drawable.wallet_issuer_cn_f5fee79339ce_card, 0xFF79412E, listOf("许昌银行")),
        WalletIssuerLogo("cn_f6820954c9e5", "台州银行", R.drawable.wallet_issuer_cn_f6820954c9e5, R.drawable.wallet_issuer_cn_f6820954c9e5_card, 0xFF6F3859, listOf("台州银行")),
        WalletIssuerLogo("cn_f844620a895e", "长治银行", R.drawable.wallet_issuer_cn_f844620a895e, R.drawable.wallet_issuer_cn_f844620a895e_card, 0xFF394B80, listOf("长治银行")),
        WalletIssuerLogo("cn_f9d2c9509592", "南阳银行", R.drawable.wallet_issuer_cn_f9d2c9509592, R.drawable.wallet_issuer_cn_f9d2c9509592_card, 0xFF6F3859, listOf("南阳银行")),
        WalletIssuerLogo("cn_fc3970d278ec", "攀枝花市商业银行", R.drawable.wallet_issuer_cn_fc3970d278ec, R.drawable.wallet_issuer_cn_fc3970d278ec_card, 0xFF315D52, listOf("攀枝花市商业银行")),
        WalletIssuerLogo("cn_feb73d528440", "哈密市商业银行", R.drawable.wallet_issuer_cn_feb73d528440, R.drawable.wallet_issuer_cn_feb73d528440_card, 0xFF244B6B, listOf("哈密市商业银行")),
        WalletIssuerLogo("commerzbank", "Commerzbank", R.drawable.wallet_issuer_commerzbank, R.drawable.wallet_issuer_commerzbank_card, 0xFF6F3859, listOf("Commerzbank", "德国商业银行")),
        WalletIssuerLogo("commonwealth", "Commonwealth Bank", R.drawable.wallet_issuer_commonwealth, R.drawable.wallet_issuer_commonwealth_card, 0xFF394B80, listOf("Commonwealth Bank", "Commonwealth Bank of Australia", "澳大利亚联邦银行")),
        WalletIssuerLogo("cqbank", "重庆银行", R.drawable.wallet_issuer_cqbank, R.drawable.wallet_issuer_cqbank_card, 0xFF6F3859, listOf("Bank of Chongqing", "重庆银行")),
        WalletIssuerLogo("cqrcb", "重庆农商", R.drawable.wallet_issuer_cqrcb, R.drawable.wallet_issuer_cqrcb_card, 0xFF246977, listOf("Chongqing Rural Commercial Bank", "重庆农商", "重庆农商银行", "重庆农村商业银行")),
        WalletIssuerLogo("crbank", "华润银行", R.drawable.wallet_issuer_crbank, R.drawable.wallet_issuer_crbank_card, 0xFF315D52, listOf("华润银行")),
        WalletIssuerLogo("cscb", "长沙银行", R.drawable.wallet_issuer_cscb, R.drawable.wallet_issuer_cscb_card, 0xFF315D52, listOf("长沙银行")),
        WalletIssuerLogo("csrcbank", "常熟农商", R.drawable.wallet_issuer_csrcbank, R.drawable.wallet_issuer_csrcbank_card, 0xFF79412E, listOf("常熟农商", "常熟农商银行", "常熟农村商业银行")),
        WalletIssuerLogo("csxbank", "三湘银行", R.drawable.wallet_issuer_csxbank, R.drawable.wallet_issuer_csxbank_card, 0xFF79412E, listOf("三湘银行")),
        WalletIssuerLogo("cycb", "朝阳银行", R.drawable.wallet_issuer_cycb, R.drawable.wallet_issuer_cycb_card, 0xFF79412E, listOf("朝阳银行")),
        WalletIssuerLogo("czbank", "浙商银行", R.drawable.wallet_issuer_czbank, R.drawable.wallet_issuer_czbank_card, 0xFF246977, listOf("China Zheshang Bank", "浙商银行")),
        WalletIssuerLogo("czcb", "浙江稠州商业银行", R.drawable.wallet_issuer_czcb, R.drawable.wallet_issuer_czcb_card, 0xFF246977, listOf("浙江稠州商业银行")),
        WalletIssuerLogo("dahsing", "大新银行", R.drawable.wallet_issuer_dahsing, R.drawable.wallet_issuer_dahsing_card, 0xFF246977, listOf("大新银行")),
        WalletIssuerLogo("dandongbank", "丹东银行", R.drawable.wallet_issuer_dandongbank, R.drawable.wallet_issuer_dandongbank_card, 0xFF6F3859, listOf("丹东银行")),
        WalletIssuerLogo("dbs", "星展银行", R.drawable.wallet_issuer_dbs, R.drawable.wallet_issuer_dbs_card, 0xFF943E44, listOf("DBS", "DBS Bank", "dbs", "星展", "星展银行")),
        WalletIssuerLogo("deutsche", "德意志银行", R.drawable.wallet_issuer_deutsche, R.drawable.wallet_issuer_deutsche_card, 0xFF244B6B, listOf("Deutsche Bank", "德意志银行")),
        WalletIssuerLogo("dongguanbank", "东莞银行", R.drawable.wallet_issuer_dongguanbank, R.drawable.wallet_issuer_dongguanbank_card, 0xFF394B80, listOf("东莞银行")),
        WalletIssuerLogo("drcbank", "东莞农商", R.drawable.wallet_issuer_drcbank, R.drawable.wallet_issuer_drcbank_card, 0xFF6F3859, listOf("东莞农商", "东莞农商银行", "东莞农村商业银行")),
        WalletIssuerLogo("dyccb", "东营银行", R.drawable.wallet_issuer_dyccb, R.drawable.wallet_issuer_dyccb_card, 0xFF394B80, listOf("东营银行")),
        WalletIssuerLogo("dzbchina", "德州银行", R.drawable.wallet_issuer_dzbchina, R.drawable.wallet_issuer_dzbchina_card, 0xFF394B80, listOf("德州银行")),
        WalletIssuerLogo("dzccb", "达州银行", R.drawable.wallet_issuer_dzccb, R.drawable.wallet_issuer_dzccb_card, 0xFF244B6B, listOf("达州银行")),
        WalletIssuerLogo("eastwestbank", "华美银行", R.drawable.wallet_issuer_eastwestbank, R.drawable.wallet_issuer_eastwestbank_card, 0xFF79412E, listOf("华美银行")),
        WalletIssuerLogo("eximbank", "中国进出口银行", R.drawable.wallet_issuer_eximbank, R.drawable.wallet_issuer_eximbank_card, 0xFF315D52, listOf("中国进出口银行")),
        WalletIssuerLogo("firstbank", "第一银行", R.drawable.wallet_issuer_firstbank, R.drawable.wallet_issuer_firstbank_card, 0xFF315D52, listOf("第一银行")),
        WalletIssuerLogo("fjhxbank", "福建海峡银行", R.drawable.wallet_issuer_fjhxbank, R.drawable.wallet_issuer_fjhxbank_card, 0xFF79412E, listOf("福建海峡银行")),
        WalletIssuerLogo("foshanbank", "佛山农商", R.drawable.wallet_issuer_foshanbank, R.drawable.wallet_issuer_foshanbank_card, 0xFF315D52, listOf("佛山农商", "佛山农商银行", "佛山农村商业银行")),
        WalletIssuerLogo("fubonchina", "富邦华一银行", R.drawable.wallet_issuer_fubonchina, R.drawable.wallet_issuer_fubonchina_card, 0xFF246977, listOf("富邦华一银行")),
        WalletIssuerLogo("fudian", "富滇银行", R.drawable.wallet_issuer_fudian, R.drawable.wallet_issuer_fudian_card, 0xFF6F3859, listOf("富滇银行")),
        WalletIssuerLogo("fuxinbank", "阜新银行", R.drawable.wallet_issuer_fuxinbank, R.drawable.wallet_issuer_fuxinbank_card, 0xFF244B6B, listOf("阜新银行")),
        WalletIssuerLogo("gdnybank", "广东南粤银行", R.drawable.wallet_issuer_gdnybank, R.drawable.wallet_issuer_gdnybank_card, 0xFF244B6B, listOf("广东南粤银行")),
        WalletIssuerLogo("ghbank", "广东华兴银行", R.drawable.wallet_issuer_ghbank, R.drawable.wallet_issuer_ghbank_card, 0xFF244B6B, listOf("广东华兴银行")),
        WalletIssuerLogo("global_adcb", "Abu Dhabi Commercial Bank", R.drawable.wallet_issuer_global_adcb, R.drawable.wallet_issuer_global_adcb_card, 0xFF79412E, listOf("Abu Dhabi Commercial Bank")),
        WalletIssuerLogo("global_apb", "Airtel Payments Bank Ltd", R.drawable.wallet_issuer_global_apb, R.drawable.wallet_issuer_global_apb_card, 0xFF315D52, listOf("Airtel Payments Bank Ltd")),
        WalletIssuerLogo("global_ausfb", "AU Small Finance Bank Ltd", R.drawable.wallet_issuer_global_ausfb, R.drawable.wallet_issuer_global_ausfb_card, 0xFF6F3859, listOf("AU Small Finance Bank Ltd")),
        WalletIssuerLogo("global_axis", "Axis Bank Ltd", R.drawable.wallet_issuer_global_axis, R.drawable.wallet_issuer_global_axis_card, 0xFF79412E, listOf("Axis Bank Ltd")),
        WalletIssuerLogo("global_bandhan", "Bandhan Bank Ltd", R.drawable.wallet_issuer_global_bandhan, R.drawable.wallet_issuer_global_bandhan_card, 0xFF315D52, listOf("Bandhan Bank Ltd")),
        WalletIssuerLogo("global_bbk", "Bank of Bahrain and Kuwait", R.drawable.wallet_issuer_global_bbk, R.drawable.wallet_issuer_global_bbk_card, 0xFF79412E, listOf("Bank of Bahrain and Kuwait")),
        WalletIssuerLogo("global_bob", "Bank of Baroda", R.drawable.wallet_issuer_global_bob, R.drawable.wallet_issuer_global_bob_card, 0xFF246977, listOf("Bank of Baroda")),
        WalletIssuerLogo("global_boi", "Bank of India", R.drawable.wallet_issuer_global_boi, R.drawable.wallet_issuer_global_boi_card, 0xFF246977, listOf("Bank of India")),
        WalletIssuerLogo("global_bom", "Bank of Maharashtra", R.drawable.wallet_issuer_global_bom, R.drawable.wallet_issuer_global_bom_card, 0xFF79412E, listOf("Bank of Maharashtra")),
    )
    private fun part3() = listOf(
        WalletIssuerLogo("global_canara", "Canara Bank", R.drawable.wallet_issuer_global_canara, R.drawable.wallet_issuer_global_canara_card, 0xFF394B80, listOf("Canara Bank")),
        WalletIssuerLogo("global_cbi", "Central Bank of India", R.drawable.wallet_issuer_global_cbi, R.drawable.wallet_issuer_global_cbi_card, 0xFF6F3859, listOf("Central Bank of India")),
        WalletIssuerLogo("global_ceylon-bank", "Bank of Ceylon", R.drawable.wallet_issuer_global_ceylon_bank, R.drawable.wallet_issuer_global_ceylon_bank_card, 0xFF315D52, listOf("Bank of Ceylon")),
        WalletIssuerLogo("global_credit-suisse", "Credit Suisse", R.drawable.wallet_issuer_global_credit_suisse, R.drawable.wallet_issuer_global_credit_suisse_card, 0xFF79412E, listOf("Credit Suisse")),
        WalletIssuerLogo("global_csb", "CSB Bank Limited", R.drawable.wallet_issuer_global_csb, R.drawable.wallet_issuer_global_csb_card, 0xFF394B80, listOf("CSB Bank Limited")),
        WalletIssuerLogo("global_cub", "City Union Bank Ltd", R.drawable.wallet_issuer_global_cub, R.drawable.wallet_issuer_global_cub_card, 0xFF6F3859, listOf("City Union Bank Ltd")),
        WalletIssuerLogo("global_dcb", "DCB Bank Ltd", R.drawable.wallet_issuer_global_dcb, R.drawable.wallet_issuer_global_dcb_card, 0xFF315D52, listOf("DCB Bank Ltd")),
        WalletIssuerLogo("global_dhanlaxmi", "Dhanlaxmi Bank Ltd", R.drawable.wallet_issuer_global_dhanlaxmi, R.drawable.wallet_issuer_global_dhanlaxmi_card, 0xFF394B80, listOf("Dhanlaxmi Bank Ltd")),
        WalletIssuerLogo("global_doha", "Doha Bank", R.drawable.wallet_issuer_global_doha, R.drawable.wallet_issuer_global_doha_card, 0xFF244B6B, listOf("Doha Bank")),
        WalletIssuerLogo("global_emirates-nbd", "Emirates NBD", R.drawable.wallet_issuer_global_emirates_nbd, R.drawable.wallet_issuer_global_emirates_nbd_card, 0xFF315D52, listOf("Emirates NBD")),
        WalletIssuerLogo("global_esaf", "ESAF Small Finance Bank Ltd", R.drawable.wallet_issuer_global_esaf, R.drawable.wallet_issuer_global_esaf_card, 0xFF79412E, listOf("ESAF Small Finance Bank Ltd")),
        WalletIssuerLogo("global_fab", "First Abu Dhabi Bank", R.drawable.wallet_issuer_global_fab, R.drawable.wallet_issuer_global_fab_card, 0xFF244B6B, listOf("First Abu Dhabi Bank")),
        WalletIssuerLogo("global_federal", "Federal Bank Ltd", R.drawable.wallet_issuer_global_federal, R.drawable.wallet_issuer_global_federal_card, 0xFF394B80, listOf("Federal Bank Ltd")),
        WalletIssuerLogo("global_fino", "FINO Payments Bank Ltd", R.drawable.wallet_issuer_global_fino, R.drawable.wallet_issuer_global_fino_card, 0xFF244B6B, listOf("FINO Payments Bank Ltd")),
        WalletIssuerLogo("global_firstrand", "FirstRand Bank", R.drawable.wallet_issuer_global_firstrand, R.drawable.wallet_issuer_global_firstrand_card, 0xFF6F3859, listOf("FirstRand Bank")),
        WalletIssuerLogo("global_handelsbanken", "Handelsbanken", R.drawable.wallet_issuer_global_handelsbanken, R.drawable.wallet_issuer_global_handelsbanken_card, 0xFF244B6B, listOf("Handelsbanken")),
        WalletIssuerLogo("global_hdfc", "HDFC Bank Ltd", R.drawable.wallet_issuer_global_hdfc, R.drawable.wallet_issuer_global_hdfc_card, 0xFF246977, listOf("HDFC Bank Ltd")),
        WalletIssuerLogo("global_icici", "ICICI Bank Ltd", R.drawable.wallet_issuer_global_icici, R.drawable.wallet_issuer_global_icici_card, 0xFF315D52, listOf("ICICI Bank Ltd")),
        WalletIssuerLogo("global_idbi", "IDBI Bank Limited", R.drawable.wallet_issuer_global_idbi, R.drawable.wallet_issuer_global_idbi_card, 0xFF394B80, listOf("IDBI Bank Limited")),
        WalletIssuerLogo("global_idfc", "IDFC FIRST Bank Limited", R.drawable.wallet_issuer_global_idfc, R.drawable.wallet_issuer_global_idfc_card, 0xFF244B6B, listOf("IDFC FIRST Bank Limited")),
        WalletIssuerLogo("global_indian", "Indian Bank", R.drawable.wallet_issuer_global_indian, R.drawable.wallet_issuer_global_indian_card, 0xFF315D52, listOf("Indian Bank")),
        WalletIssuerLogo("global_indiapost", "India Post Payments Bank Ltd", R.drawable.wallet_issuer_global_indiapost, R.drawable.wallet_issuer_global_indiapost_card, 0xFF315D52, listOf("India Post Payments Bank Ltd")),
        WalletIssuerLogo("global_indus", "IndusInd Bank Ltd", R.drawable.wallet_issuer_global_indus, R.drawable.wallet_issuer_global_indus_card, 0xFF315D52, listOf("IndusInd Bank Ltd")),
        WalletIssuerLogo("global_iob", "Indian Overseas Bank", R.drawable.wallet_issuer_global_iob, R.drawable.wallet_issuer_global_iob_card, 0xFF6F3859, listOf("Indian Overseas Bank")),
        WalletIssuerLogo("global_jio", "Jio Payments Bank Ltd", R.drawable.wallet_issuer_global_jio, R.drawable.wallet_issuer_global_jio_card, 0xFF79412E, listOf("Jio Payments Bank Ltd")),
        WalletIssuerLogo("global_jnk", "Jammu & Kashmir Bank Ltd", R.drawable.wallet_issuer_global_jnk, R.drawable.wallet_issuer_global_jnk_card, 0xFF244B6B, listOf("Jammu & Kashmir Bank Ltd")),
        WalletIssuerLogo("global_karnataka", "Karnataka Bank Ltd", R.drawable.wallet_issuer_global_karnataka, R.drawable.wallet_issuer_global_karnataka_card, 0xFF79412E, listOf("Karnataka Bank Ltd")),
        WalletIssuerLogo("global_korea-bank", "Industrial Bank of Korea", R.drawable.wallet_issuer_global_korea_bank, R.drawable.wallet_issuer_global_korea_bank_card, 0xFF315D52, listOf("Industrial Bank of Korea")),
        WalletIssuerLogo("global_kotak", "Kotak Mahindra Bank Ltd", R.drawable.wallet_issuer_global_kotak, R.drawable.wallet_issuer_global_kotak_card, 0xFF315D52, listOf("Kotak Mahindra Bank Ltd")),
        WalletIssuerLogo("global_krungthai", "Krung Thai Bank", R.drawable.wallet_issuer_global_krungthai, R.drawable.wallet_issuer_global_krungthai_card, 0xFF315D52, listOf("Krung Thai Bank")),
        WalletIssuerLogo("global_kvb", "Karur Vysya Bank Ltd", R.drawable.wallet_issuer_global_kvb, R.drawable.wallet_issuer_global_kvb_card, 0xFF394B80, listOf("Karur Vysya Bank Ltd")),
        WalletIssuerLogo("global_ntb", "Nainital Bank Ltd", R.drawable.wallet_issuer_global_ntb, R.drawable.wallet_issuer_global_ntb_card, 0xFF244B6B, listOf("Nainital Bank Ltd")),
        WalletIssuerLogo("global_paytm", "Paytm Payments Bank Ltd", R.drawable.wallet_issuer_global_paytm, R.drawable.wallet_issuer_global_paytm_card, 0xFF6F3859, listOf("Paytm Payments Bank Ltd")),
        WalletIssuerLogo("global_pnb", "Punjab National Bank", R.drawable.wallet_issuer_global_pnb, R.drawable.wallet_issuer_global_pnb_card, 0xFF394B80, listOf("Punjab National Bank")),
        WalletIssuerLogo("global_psb", "Punjab & Sind Bank", R.drawable.wallet_issuer_global_psb, R.drawable.wallet_issuer_global_psb_card, 0xFF315D52, listOf("Punjab & Sind Bank")),
        WalletIssuerLogo("global_qnb", "Qatar National Bank", R.drawable.wallet_issuer_global_qnb, R.drawable.wallet_issuer_global_qnb_card, 0xFF315D52, listOf("Qatar National Bank")),
        WalletIssuerLogo("global_rbl", "RBL Bank Ltd", R.drawable.wallet_issuer_global_rbl, R.drawable.wallet_issuer_global_rbl_card, 0xFF315D52, listOf("RBL Bank Ltd")),
        WalletIssuerLogo("global_saxo", "Saxo Bank", R.drawable.wallet_issuer_global_saxo, R.drawable.wallet_issuer_global_saxo_card, 0xFF315D52, listOf("Saxo Bank")),
        WalletIssuerLogo("global_sberbank", "Sberbank", R.drawable.wallet_issuer_global_sberbank, R.drawable.wallet_issuer_global_sberbank_card, 0xFF315D52, listOf("Sberbank")),
        WalletIssuerLogo("global_sbi", "State Bank of India", R.drawable.wallet_issuer_global_sbi, R.drawable.wallet_issuer_global_sbi_card, 0xFF79412E, listOf("State Bank of India")),
        WalletIssuerLogo("global_sib", "South Indian Bank Ltd", R.drawable.wallet_issuer_global_sib, R.drawable.wallet_issuer_global_sib_card, 0xFF244B6B, listOf("South Indian Bank Ltd")),
        WalletIssuerLogo("global_sonali", "Sonali Bank", R.drawable.wallet_issuer_global_sonali, R.drawable.wallet_issuer_global_sonali_card, 0xFF244B6B, listOf("Sonali Bank")),
        WalletIssuerLogo("global_tmb", "Tamilnad Mercantile Bank Ltd", R.drawable.wallet_issuer_global_tmb, R.drawable.wallet_issuer_global_tmb_card, 0xFF244B6B, listOf("Tamilnad Mercantile Bank Ltd")),
        WalletIssuerLogo("global_ubi", "Union Bank of India", R.drawable.wallet_issuer_global_ubi, R.drawable.wallet_issuer_global_ubi_card, 0xFF79412E, listOf("Union Bank of India")),
        WalletIssuerLogo("global_uco", "UCO Bank", R.drawable.wallet_issuer_global_uco, R.drawable.wallet_issuer_global_uco_card, 0xFF394B80, listOf("UCO Bank")),
        WalletIssuerLogo("global_ujjivan", "Ujjivan Small Finance Bank Ltd", R.drawable.wallet_issuer_global_ujjivan, R.drawable.wallet_issuer_global_ujjivan_card, 0xFF79412E, listOf("Ujjivan Small Finance Bank Ltd")),
        WalletIssuerLogo("global_yes", "YES Bank Ltd", R.drawable.wallet_issuer_global_yes, R.drawable.wallet_issuer_global_yes_card, 0xFF6F3859, listOf("YES Bank Ltd")),
        WalletIssuerLogo("grcbank", "广东农商", R.drawable.wallet_issuer_grcbank, R.drawable.wallet_issuer_grcbank_card, 0xFF6F3859, listOf("广东农商", "广东农商银行", "广东农村商业银行")),
        WalletIssuerLogo("gsbankchina", "甘肃银行", R.drawable.wallet_issuer_gsbankchina, R.drawable.wallet_issuer_gsbankchina_card, 0xFF246977, listOf("甘肃银行")),
        WalletIssuerLogo("guilinbank", "桂林银行", R.drawable.wallet_issuer_guilinbank, R.drawable.wallet_issuer_guilinbank_card, 0xFF6F3859, listOf("桂林银行")),
        WalletIssuerLogo("gx966888", "广西农村信用社", R.drawable.wallet_issuer_gx966888, R.drawable.wallet_issuer_gx966888_card, 0xFF246977, listOf("广西农村信用社")),
        WalletIssuerLogo("gzcb", "广州银行", R.drawable.wallet_issuer_gzcb, R.drawable.wallet_issuer_gzcb_card, 0xFF394B80, listOf("广州银行")),
        WalletIssuerLogo("gzccb", "赣州银行", R.drawable.wallet_issuer_gzccb, R.drawable.wallet_issuer_gzccb_card, 0xFF79412E, listOf("赣州银行")),
        WalletIssuerLogo("hana", "韩亚银行", R.drawable.wallet_issuer_hana, R.drawable.wallet_issuer_hana_card, 0xFF315D52, listOf("Hana Bank", "KEB Hana Bank", "韩亚银行")),
        WalletIssuerLogo("hangseng", "恒生银行", R.drawable.wallet_issuer_hangseng, R.drawable.wallet_issuer_hangseng_card, 0xFF356A50, listOf("Hang Seng Bank", "hangseng", "恆生", "恆生銀行", "恒生", "恒生银行")),
        WalletIssuerLogo("hdcb", "邯郸银行", R.drawable.wallet_issuer_hdcb, R.drawable.wallet_issuer_hdcb_card, 0xFF315D52, listOf("邯郸银行")),
        WalletIssuerLogo("hebbank", "河北银行", R.drawable.wallet_issuer_hebbank, R.drawable.wallet_issuer_hebbank_card, 0xFF246977, listOf("河北银行")),
        WalletIssuerLogo("hfbank", "恒丰银行", R.drawable.wallet_issuer_hfbank, R.drawable.wallet_issuer_hfbank_card, 0xFF79412E, listOf("恒丰银行")),
        WalletIssuerLogo("hfrcbc", "合肥科技农商", R.drawable.wallet_issuer_hfrcbc, R.drawable.wallet_issuer_hfrcbc_card, 0xFF79412E, listOf("合肥科技农商", "合肥科技农商银行", "合肥科技农村商业银行")),
        WalletIssuerLogo("hkbchina", "汉口银行", R.drawable.wallet_issuer_hkbchina, R.drawable.wallet_issuer_hkbchina_card, 0xFF315D52, listOf("汉口银行")),
    )
    private fun part4() = listOf(
        WalletIssuerLogo("hnnxs", "湖南省农村信用社", R.drawable.wallet_issuer_hnnxs, R.drawable.wallet_issuer_hnnxs_card, 0xFF394B80, listOf("湖南省农村信用社")),
        WalletIssuerLogo("hrbb", "哈尔滨银行", R.drawable.wallet_issuer_hrbb, R.drawable.wallet_issuer_hrbb_card, 0xFF394B80, listOf("哈尔滨银行")),
        WalletIssuerLogo("hrxjbank", "华融湘江银行", R.drawable.wallet_issuer_hrxjbank, R.drawable.wallet_issuer_hrxjbank_card, 0xFF394B80, listOf("华融湘江银行")),
        WalletIssuerLogo("hsbank", "徽商银行", R.drawable.wallet_issuer_hsbank, R.drawable.wallet_issuer_hsbank_card, 0xFF246977, listOf("Huishang Bank", "徽商银行")),
        WalletIssuerLogo("hsbc", "汇丰银行", R.drawable.wallet_issuer_hsbc, R.drawable.wallet_issuer_hsbc_card, 0xFF444B53, listOf("HSBC", "hsbc", "匯豐", "汇丰", "汇丰银行", "滙豐", "滙豐銀行")),
        WalletIssuerLogo("hubeibank", "湖北银行", R.drawable.wallet_issuer_hubeibank, R.drawable.wallet_issuer_hubeibank_card, 0xFF79412E, listOf("湖北银行")),
        WalletIssuerLogo("hxb", "华夏银行", R.drawable.wallet_issuer_hxb, R.drawable.wallet_issuer_hxb_card, 0xFF984944, listOf("huaxiabank", "hxb", "华夏银行", "華夏銀行")),
        WalletIssuerLogo("hzbank", "杭州银行", R.drawable.wallet_issuer_hzbank, R.drawable.wallet_issuer_hzbank_card, 0xFF315D52, listOf("Bank of Hangzhou", "杭州银行")),
        WalletIssuerLogo("hzccb", "湖州银行", R.drawable.wallet_issuer_hzccb, R.drawable.wallet_issuer_hzccb_card, 0xFF244B6B, listOf("湖州银行")),
        WalletIssuerLogo("hznsyh", "惠州农商", R.drawable.wallet_issuer_hznsyh, R.drawable.wallet_issuer_hznsyh_card, 0xFF6F3859, listOf("惠州农商", "惠州农商银行", "惠州农村商业银行")),
        WalletIssuerLogo("ibk", "韩国企业银行", R.drawable.wallet_issuer_ibk, R.drawable.wallet_issuer_ibk_card, 0xFF79412E, listOf("韩国企业银行")),
        WalletIssuerLogo("icbc", "中国工商银行", R.drawable.wallet_issuer_icbc, R.drawable.wallet_issuer_icbc_card, 0xFF9F343D, listOf("Industrial & Commercial Bank of China", "Industrial and Commercial Bank of China", "icbc", "industrialandcommercialbank", "中国工商银行", "工商銀行", "工商银行", "工行")),
        WalletIssuerLogo("jhccb", "金华银行", R.drawable.wallet_issuer_jhccb, R.drawable.wallet_issuer_jhccb_card, 0xFF394B80, listOf("金华银行")),
        WalletIssuerLogo("jhrcbank", "建湖农商", R.drawable.wallet_issuer_jhrcbank, R.drawable.wallet_issuer_jhrcbank_card, 0xFF79412E, listOf("建湖农商", "建湖农商银行", "建湖农村商业银行")),
        WalletIssuerLogo("jinzhoubank", "锦州银行", R.drawable.wallet_issuer_jinzhoubank, R.drawable.wallet_issuer_jinzhoubank_card, 0xFF244B6B, listOf("锦州银行")),
        WalletIssuerLogo("jjbank", "江苏靖江农商", R.drawable.wallet_issuer_jjbank, R.drawable.wallet_issuer_jjbank_card, 0xFF315D52, listOf("江苏靖江农商", "江苏靖江农商银行", "江苏靖江农村商业银行")),
        WalletIssuerLogo("jjccb", "九江银行", R.drawable.wallet_issuer_jjccb, R.drawable.wallet_issuer_jjccb_card, 0xFF6F3859, listOf("九江银行")),
        WalletIssuerLogo("jlbank", "吉林银行", R.drawable.wallet_issuer_jlbank, R.drawable.wallet_issuer_jlbank_card, 0xFF79412E, listOf("吉林银行")),
        WalletIssuerLogo("jmrcb", "江门农商", R.drawable.wallet_issuer_jmrcb, R.drawable.wallet_issuer_jmrcb_card, 0xFF246977, listOf("江门农商", "江门农商银行", "江门农村商业银行")),
        WalletIssuerLogo("jn-bank", "济宁银行", R.drawable.wallet_issuer_jn_bank, R.drawable.wallet_issuer_jn_bank_card, 0xFF394B80, listOf("济宁银行")),
        WalletIssuerLogo("jrnsh", "江苏句容农商", R.drawable.wallet_issuer_jrnsh, R.drawable.wallet_issuer_jrnsh_card, 0xFF244B6B, listOf("江苏句容农商", "江苏句容农商银行", "江苏句容农村商业银行")),
        WalletIssuerLogo("jsbchina", "江苏银行", R.drawable.wallet_issuer_jsbchina, R.drawable.wallet_issuer_jsbchina_card, 0xFF246977, listOf("Bank of Jiangsu", "江苏银行")),
        WalletIssuerLogo("jshbank", "晋商银行", R.drawable.wallet_issuer_jshbank, R.drawable.wallet_issuer_jshbank_card, 0xFF6F3859, listOf("晋商银行")),
        WalletIssuerLogo("jsyxrcb", "江苏宜兴农商", R.drawable.wallet_issuer_jsyxrcb, R.drawable.wallet_issuer_jsyxrcb_card, 0xFF6F3859, listOf("江苏宜兴农商", "江苏宜兴农商银行", "江苏宜兴农村商业银行")),
        WalletIssuerLogo("jtnsh", "九台农商", R.drawable.wallet_issuer_jtnsh, R.drawable.wallet_issuer_jtnsh_card, 0xFF244B6B, listOf("九台农商", "九台农商银行", "九台农村商业银行")),
        WalletIssuerLogo("jx-bank", "江西银行", R.drawable.wallet_issuer_jx_bank, R.drawable.wallet_issuer_jx_bank_card, 0xFF244B6B, listOf("江西银行")),
        WalletIssuerLogo("jybank", "江阴农商", R.drawable.wallet_issuer_jybank, R.drawable.wallet_issuer_jybank_card, 0xFF394B80, listOf("江阴农商", "江阴农商银行", "江阴农村商业银行")),
        WalletIssuerLogo("kbstarchina", "韩国国民银行", R.drawable.wallet_issuer_kbstarchina, R.drawable.wallet_issuer_kbstarchina_card, 0xFF246977, listOf("韩国国民银行")),
        WalletIssuerLogo("klb", "昆仑银行", R.drawable.wallet_issuer_klb, R.drawable.wallet_issuer_klb_card, 0xFF394B80, listOf("昆仑银行")),
        WalletIssuerLogo("kookmin", "Kookmin Bank", R.drawable.wallet_issuer_kookmin, R.drawable.wallet_issuer_kookmin_card, 0xFF244B6B, listOf("KB Kookmin Bank", "KB国民银行", "Kookmin Bank")),
        WalletIssuerLogo("ksrcb", "昆山农商", R.drawable.wallet_issuer_ksrcb, R.drawable.wallet_issuer_ksrcb_card, 0xFF394B80, listOf("昆山农商", "昆山农商银行", "昆山农村商业银行")),
        WalletIssuerLogo("lccb", "廊坊银行", R.drawable.wallet_issuer_lccb, R.drawable.wallet_issuer_lccb_card, 0xFF79412E, listOf("廊坊银行")),
        WalletIssuerLogo("lj-bank", "龙江银行", R.drawable.wallet_issuer_lj_bank, R.drawable.wallet_issuer_lj_bank_card, 0xFF315D52, listOf("龙江银行")),
        WalletIssuerLogo("lqrcb", "路桥农村合作银行", R.drawable.wallet_issuer_lqrcb, R.drawable.wallet_issuer_lqrcb_card, 0xFF244B6B, listOf("路桥农村合作银行")),
        WalletIssuerLogo("lsbankchina", "莱商银行", R.drawable.wallet_issuer_lsbankchina, R.drawable.wallet_issuer_lsbankchina_card, 0xFF6F3859, listOf("莱商银行")),
        WalletIssuerLogo("lsbchina", "临商银行", R.drawable.wallet_issuer_lsbchina, R.drawable.wallet_issuer_lsbchina_card, 0xFF79412E, listOf("临商银行")),
        WalletIssuerLogo("lsccb", "乐山市商业银行", R.drawable.wallet_issuer_lsccb, R.drawable.wallet_issuer_lsccb_card, 0xFF315D52, listOf("乐山市商业银行")),
        WalletIssuerLogo("luoyang-szgold", "洛阳银行", R.drawable.wallet_issuer_luoyang_szgold, R.drawable.wallet_issuer_luoyang_szgold_card, 0xFF394B80, listOf("洛阳银行")),
        WalletIssuerLogo("lygdfrcb", "连云港东方农商", R.drawable.wallet_issuer_lygdfrcb, R.drawable.wallet_issuer_lygdfrcb_card, 0xFF6F3859, listOf("连云港东方农商", "连云港东方农商银行", "连云港东方农村商业银行")),
        WalletIssuerLogo("lzbank", "兰州银行", R.drawable.wallet_issuer_lzbank, R.drawable.wallet_issuer_lzbank_card, 0xFF79412E, listOf("兰州银行")),
        WalletIssuerLogo("lzccb", "泸州银行", R.drawable.wallet_issuer_lzccb, R.drawable.wallet_issuer_lzccb_card, 0xFF394B80, listOf("泸州银行")),
        WalletIssuerLogo("masrcb", "马鞍山农商", R.drawable.wallet_issuer_masrcb, R.drawable.wallet_issuer_masrcb_card, 0xFF246977, listOf("马鞍山农商", "马鞍山农商银行", "马鞍山农村商业银行")),
        WalletIssuerLogo("maybank", "马来亚银行", R.drawable.wallet_issuer_maybank, R.drawable.wallet_issuer_maybank_card, 0xFF79412E, listOf("Bank Maybank Indonesia", "Maybank", "马来亚银行")),
        WalletIssuerLogo("megabank", "兆丰国际商业银行", R.drawable.wallet_issuer_megabank, R.drawable.wallet_issuer_megabank_card, 0xFF79412E, listOf("兆丰国际商业银行")),
        WalletIssuerLogo("meigin", "名古屋银行", R.drawable.wallet_issuer_meigin, R.drawable.wallet_issuer_meigin_card, 0xFF6F3859, listOf("名古屋银行")),
        WalletIssuerLogo("mintaibank", "浙江民泰商行", R.drawable.wallet_issuer_mintaibank, R.drawable.wallet_issuer_mintaibank_card, 0xFF246977, listOf("浙江民泰商行")),
        WalletIssuerLogo("mizuho", "Mizuho Corporate Bank", R.drawable.wallet_issuer_mizuho, R.drawable.wallet_issuer_mizuho_card, 0xFF244B6B, listOf("Mizuho Bank", "Mizuho Corporate Bank", "瑞穗银行")),
        WalletIssuerLogo("monzo", "Monzo", R.drawable.wallet_issuer_monzo, R.drawable.wallet_issuer_monzo_card, 0xFF6F3859, listOf("Monzo", "Monzo Bank")),
        WalletIssuerLogo("mufg", "东京三菱银行", R.drawable.wallet_issuer_mufg, R.drawable.wallet_issuer_mufg_card, 0xFF315D52, listOf("MUFG", "MUFG Bank", "三菱日联银行", "东京三菱银行")),
        WalletIssuerLogo("mycc", "绵阳商业银行", R.drawable.wallet_issuer_mycc, R.drawable.wallet_issuer_mycc_card, 0xFF246977, listOf("绵阳商业银行")),
        WalletIssuerLogo("n26", "N26", R.drawable.wallet_issuer_n26, R.drawable.wallet_issuer_n26_card, 0xFF315D52, listOf("N26", "N26 Bank")),
        WalletIssuerLogo("nab", "National Australia Bank", R.drawable.wallet_issuer_nab, R.drawable.wallet_issuer_nab_card, 0xFF79412E, listOf("NAB", "National Australia Bank", "澳大利亚国民银行")),
        WalletIssuerLogo("nanhaibank", "南海农商", R.drawable.wallet_issuer_nanhaibank, R.drawable.wallet_issuer_nanhaibank_card, 0xFF246977, listOf("南海农商", "南海农商银行", "南海农村商业银行")),
        WalletIssuerLogo("natwest", "NatWest Group", R.drawable.wallet_issuer_natwest, R.drawable.wallet_issuer_natwest_card, 0xFF244B6B, listOf("NatWest", "NatWest Group", "National Westminster Bank")),
        WalletIssuerLogo("nbcb", "宁波银行", R.drawable.wallet_issuer_nbcb, R.drawable.wallet_issuer_nbcb_card, 0xFF79412E, listOf("Bank of Ningbo", "宁波银行")),
        WalletIssuerLogo("ncbank", "宁波通商银行", R.drawable.wallet_issuer_ncbank, R.drawable.wallet_issuer_ncbank_card, 0xFF79412E, listOf("宁波通商银行")),
        WalletIssuerLogo("ncbchina", "南洋商业银行", R.drawable.wallet_issuer_ncbchina, R.drawable.wallet_issuer_ncbchina_card, 0xFF394B80, listOf("南洋商业银行")),
        WalletIssuerLogo("njcb", "南京银行", R.drawable.wallet_issuer_njcb, R.drawable.wallet_issuer_njcb_card, 0xFF315D52, listOf("Bank of Nanjing", "南京银行")),
        WalletIssuerLogo("nubank", "Nubank", R.drawable.wallet_issuer_nubank, R.drawable.wallet_issuer_nubank_card, 0xFF394B80, listOf("Nu Bank", "Nubank")),
        WalletIssuerLogo("o-bank", "王道银行", R.drawable.wallet_issuer_o_bank, R.drawable.wallet_issuer_o_bank_card, 0xFF315D52, listOf("王道银行")),
    )
    private fun part5() = listOf(
        WalletIssuerLogo("ocbc", "华侨永亨银行", R.drawable.wallet_issuer_ocbc, R.drawable.wallet_issuer_ocbc_card, 0xFF394B80, listOf("OCBC", "OCBC Bank", "Oversea-Chinese Banking Corporation", "华侨永亨银行", "华侨银行")),
        WalletIssuerLogo("ordosbank", "鄂尔多斯银行", R.drawable.wallet_issuer_ordosbank, R.drawable.wallet_issuer_ordosbank_card, 0xFF244B6B, listOf("鄂尔多斯银行")),
        WalletIssuerLogo("paypal", "PayPal", R.drawable.wallet_issuer_paypal, R.drawable.wallet_issuer_paypal_card, 0xFF394B80, listOf("PayPal")),
        WalletIssuerLogo("pingan", "平安银行", R.drawable.wallet_issuer_pingan, R.drawable.wallet_issuer_pingan_card, 0xFF975D2E, listOf("pinganbank", "平安銀行", "平安银行")),
        WalletIssuerLogo("psbc", "中国邮政储蓄银行", R.drawable.wallet_issuer_psbc, R.drawable.wallet_issuer_psbc_card, 0xFF416C50, listOf("Postal Savings Bank of China", "postalsavingsbank", "psbc", "中国邮政储蓄银行", "邮储银行", "邮政储蓄", "邮政储蓄银行", "郵政儲蓄")),
        WalletIssuerLogo("qdccb", "青岛银行", R.drawable.wallet_issuer_qdccb, R.drawable.wallet_issuer_qdccb_card, 0xFF244B6B, listOf("青岛银行")),
        WalletIssuerLogo("qhdbank", "秦皇岛银行", R.drawable.wallet_issuer_qhdbank, R.drawable.wallet_issuer_qhdbank_card, 0xFF244B6B, listOf("秦皇岛银行")),
        WalletIssuerLogo("qingbank", "清远农商", R.drawable.wallet_issuer_qingbank, R.drawable.wallet_issuer_qingbank_card, 0xFF315D52, listOf("清远农商", "清远农商银行", "清远农村商业银行")),
        WalletIssuerLogo("qjccb", "曲靖市商业银行", R.drawable.wallet_issuer_qjccb, R.drawable.wallet_issuer_qjccb_card, 0xFF244B6B, listOf("曲靖市商业银行")),
        WalletIssuerLogo("qlbchina", "齐鲁银行", R.drawable.wallet_issuer_qlbchina, R.drawable.wallet_issuer_qlbchina_card, 0xFF394B80, listOf("齐鲁银行")),
        WalletIssuerLogo("qsbank", "齐商银行", R.drawable.wallet_issuer_qsbank, R.drawable.wallet_issuer_qsbank_card, 0xFF246977, listOf("齐商银行")),
        WalletIssuerLogo("qzccbank", "泉州银行", R.drawable.wallet_issuer_qzccbank, R.drawable.wallet_issuer_qzccbank_card, 0xFF244B6B, listOf("泉州银行")),
        WalletIssuerLogo("rabobank", "Rabobank", R.drawable.wallet_issuer_rabobank, R.drawable.wallet_issuer_rabobank_card, 0xFF244B6B, listOf("Rabobank", "荷兰合作银行")),
        WalletIssuerLogo("rbcroyalbank", "加拿大皇家银行", R.drawable.wallet_issuer_rbcroyalbank, R.drawable.wallet_issuer_rbcroyalbank_card, 0xFF315D52, listOf("RBC", "RBC Royal Bank", "Royal Bank of Canada", "加拿大皇家银行")),
        WalletIssuerLogo("revolut", "Revolut", R.drawable.wallet_issuer_revolut, R.drawable.wallet_issuer_revolut_card, 0xFF315D52, listOf("Revolut", "Revolut Bank")),
        WalletIssuerLogo("sc", "渣打银行", R.drawable.wallet_issuer_sc, R.drawable.wallet_issuer_sc_card, 0xFF3C6B68, listOf("Standard Chartered", "Standard Chartered Bank", "standardchartered", "渣打", "渣打银行")),
        WalletIssuerLogo("scnhh", "安徽舒城农村商业银行", R.drawable.wallet_issuer_scnhh, R.drawable.wallet_issuer_scnhh_card, 0xFF394B80, listOf("安徽舒城农商", "安徽舒城农商银行", "安徽舒城农村商业银行")),
        WalletIssuerLogo("scotia", "加拿大丰业银行", R.drawable.wallet_issuer_scotia, R.drawable.wallet_issuer_scotia_card, 0xFF315D52, listOf("Scotia", "Scotiabank", "加拿大丰业银行")),
        WalletIssuerLogo("sdebank", "顺德农商", R.drawable.wallet_issuer_sdebank, R.drawable.wallet_issuer_sdebank_card, 0xFF315D52, listOf("顺德农商", "顺德农商银行", "顺德农村商业银行")),
        WalletIssuerLogo("sdnxs", "山东省农村信用社", R.drawable.wallet_issuer_sdnxs, R.drawable.wallet_issuer_sdnxs_card, 0xFF79412E, listOf("山东省农村信用社")),
        WalletIssuerLogo("sgb", "中德住房储蓄银行", R.drawable.wallet_issuer_sgb, R.drawable.wallet_issuer_sgb_card, 0xFF79412E, listOf("中德住房储蓄银行")),
        WalletIssuerLogo("shengjingbank", "盛京银行", R.drawable.wallet_issuer_shengjingbank, R.drawable.wallet_issuer_shengjingbank_card, 0xFF244B6B, listOf("盛京银行")),
        WalletIssuerLogo("shinhan", "新韩银行", R.drawable.wallet_issuer_shinhan, R.drawable.wallet_issuer_shinhan_card, 0xFF79412E, listOf("Shinhan Bank", "新韩银行")),
        WalletIssuerLogo("sinopac", "永丰银行", R.drawable.wallet_issuer_sinopac, R.drawable.wallet_issuer_sinopac_card, 0xFF315D52, listOf("永丰银行")),
        WalletIssuerLogo("smbc", "三井住友银行", R.drawable.wallet_issuer_smbc, R.drawable.wallet_issuer_smbc_card, 0xFF6F3859, listOf("SMBC", "Sumitomo Mitsui Banking Corporation", "三井住友银行")),
        WalletIssuerLogo("snccb", "遂宁银行", R.drawable.wallet_issuer_snccb, R.drawable.wallet_issuer_snccb_card, 0xFF6F3859, listOf("遂宁银行")),
        WalletIssuerLogo("societe_generale", "Société Générale", R.drawable.wallet_issuer_societe_generale, R.drawable.wallet_issuer_societe_generale_card, 0xFF394B80, listOf("Societe Generale", "Société Générale", "法国兴业银行")),
        WalletIssuerLogo("societegenerale", "法兴银行", R.drawable.wallet_issuer_societegenerale, R.drawable.wallet_issuer_societegenerale_card, 0xFF6F3859, listOf("法兴银行")),
        WalletIssuerLogo("spdb", "浦发银行", R.drawable.wallet_issuer_spdb, R.drawable.wallet_issuer_spdb_card, 0xFF375987, listOf("shanghaipudongdevelopment", "spdb", "浦发银行", "浦發銀行")),
        WalletIssuerLogo("srbank", "上饶银行", R.drawable.wallet_issuer_srbank, R.drawable.wallet_issuer_srbank_card, 0xFF394B80, listOf("上饶银行")),
        WalletIssuerLogo("srcb", "上海农商", R.drawable.wallet_issuer_srcb, R.drawable.wallet_issuer_srcb_card, 0xFF315D52, listOf("Shanghai Rural Commercial Bank", "上海农商", "上海农商银行", "上海农村商业银行")),
        WalletIssuerLogo("starlingbank", "Starling Bank", R.drawable.wallet_issuer_starlingbank, R.drawable.wallet_issuer_starlingbank_card, 0xFF6F3859, listOf("Starling", "Starling Bank")),
        WalletIssuerLogo("suzhoubank", "苏州银行", R.drawable.wallet_issuer_suzhoubank, R.drawable.wallet_issuer_suzhoubank_card, 0xFF394B80, listOf("苏州银行")),
        WalletIssuerLogo("sxccb", "绍兴银行", R.drawable.wallet_issuer_sxccb, R.drawable.wallet_issuer_sxccb_card, 0xFF6F3859, listOf("绍兴银行")),
        WalletIssuerLogo("syrcb", "江苏射阳农商银行", R.drawable.wallet_issuer_syrcb, R.drawable.wallet_issuer_syrcb_card, 0xFF6F3859, listOf("江苏射阳农商银行")),
        WalletIssuerLogo("szsccb", "石嘴山银行", R.drawable.wallet_issuer_szsccb, R.drawable.wallet_issuer_szsccb_card, 0xFF246977, listOf("石嘴山银行")),
        WalletIssuerLogo("taccb", "泰安银行", R.drawable.wallet_issuer_taccb, R.drawable.wallet_issuer_taccb_card, 0xFF246977, listOf("泰安银行")),
        WalletIssuerLogo("tcb-bank", "合作金库银行", R.drawable.wallet_issuer_tcb_bank, R.drawable.wallet_issuer_tcb_bank_card, 0xFF394B80, listOf("合作金库银行")),
        WalletIssuerLogo("td", "TD Bank", R.drawable.wallet_issuer_td, R.drawable.wallet_issuer_td_card, 0xFF244B6B, listOf("TD Bank", "TD Canada Trust", "Toronto-Dominion Bank", "道明银行")),
        WalletIssuerLogo("tf", "四川天府银行", R.drawable.wallet_issuer_tf, R.drawable.wallet_issuer_tf_card, 0xFF79412E, listOf("四川天府银行")),
        WalletIssuerLogo("tjbhb", "天津滨海农商", R.drawable.wallet_issuer_tjbhb, R.drawable.wallet_issuer_tjbhb_card, 0xFF246977, listOf("天津滨海农商", "天津滨海农商银行", "天津滨海农村商业银行")),
        WalletIssuerLogo("trcbank", "天津农商", R.drawable.wallet_issuer_trcbank, R.drawable.wallet_issuer_trcbank_card, 0xFF315D52, listOf("天津农商", "天津农商银行", "天津农村商业银行")),
        WalletIssuerLogo("ts-bank", "唐山银行", R.drawable.wallet_issuer_ts_bank, R.drawable.wallet_issuer_ts_bank_card, 0xFF244B6B, listOf("唐山银行")),
        WalletIssuerLogo("ubs", "瑞士银行", R.drawable.wallet_issuer_ubs, R.drawable.wallet_issuer_ubs_card, 0xFF315D52, listOf("UBS", "瑞士银行", "瑞銀", "瑞银")),
        WalletIssuerLogo("uccb", "乌鲁木齐商业银行", R.drawable.wallet_issuer_uccb, R.drawable.wallet_issuer_uccb_card, 0xFF315D52, listOf("乌鲁木齐商业银行")),
        WalletIssuerLogo("uob", "大华银行", R.drawable.wallet_issuer_uob, R.drawable.wallet_issuer_uob_card, 0xFF6F3859, listOf("UOB", "United Overseas Bank", "大华银行")),
        WalletIssuerLogo("urcb", "杭州联合银行", R.drawable.wallet_issuer_urcb, R.drawable.wallet_issuer_urcb_card, 0xFF394B80, listOf("杭州联合银行")),
        WalletIssuerLogo("wells", "Wells Fargo", R.drawable.wallet_issuer_wells, R.drawable.wallet_issuer_wells_card, 0xFF79412E, listOf("Wells Fargo", "Wells Fargo Bank", "富国银行")),
        WalletIssuerLogo("westpac", "Westpac", R.drawable.wallet_issuer_westpac, R.drawable.wallet_issuer_westpac_card, 0xFF394B80, listOf("Westpac", "西太平洋银行")),
        WalletIssuerLogo("whrcbank", "武汉农商", R.drawable.wallet_issuer_whrcbank, R.drawable.wallet_issuer_whrcbank_card, 0xFF244B6B, listOf("武汉农商", "武汉农商银行", "武汉农村商业银行")),
        WalletIssuerLogo("wise", "Wise", R.drawable.wallet_issuer_wise, R.drawable.wallet_issuer_wise_card, 0xFF6F3859, listOf("TransferWise", "Wise")),
        WalletIssuerLogo("woori", "Woori Bank", R.drawable.wallet_issuer_woori, R.drawable.wallet_issuer_woori_card, 0xFF394B80, listOf("Woori Bank", "友利银行")),
        WalletIssuerLogo("wrcb", "无锡农商", R.drawable.wallet_issuer_wrcb, R.drawable.wallet_issuer_wrcb_card, 0xFF246977, listOf("无锡农商", "无锡农商银行", "无锡农村商业银行")),
        WalletIssuerLogo("wuhaicb", "乌海银行", R.drawable.wallet_issuer_wuhaicb, R.drawable.wallet_issuer_wuhaicb_card, 0xFF315D52, listOf("乌海银行")),
        WalletIssuerLogo("wzcb", "温州银行", R.drawable.wallet_issuer_wzcb, R.drawable.wallet_issuer_wzcb_card, 0xFF246977, listOf("温州银行")),
        WalletIssuerLogo("xacbank", "西安银行", R.drawable.wallet_issuer_xacbank, R.drawable.wallet_issuer_xacbank_card, 0xFF246977, listOf("西安银行")),
        WalletIssuerLogo("xib", "厦门国际银行", R.drawable.wallet_issuer_xib, R.drawable.wallet_issuer_xib_card, 0xFF246977, listOf("厦门国际银行")),
        WalletIssuerLogo("xjkccb", "库尔勒市商业银行", R.drawable.wallet_issuer_xjkccb, R.drawable.wallet_issuer_xjkccb_card, 0xFF79412E, listOf("库尔勒市商业银行")),
        WalletIssuerLogo("xmbankonline", "厦门银行", R.drawable.wallet_issuer_xmbankonline, R.drawable.wallet_issuer_xmbankonline_card, 0xFF394B80, listOf("Bank of Xiamen", "厦门银行")),
        WalletIssuerLogo("xynsh", "新沂农商", R.drawable.wallet_issuer_xynsh, R.drawable.wallet_issuer_xynsh_card, 0xFF315D52, listOf("新沂农商", "新沂农商银行", "新沂农村商业银行")),
    )
    private fun part6() = listOf(
        WalletIssuerLogo("yamaguchibank", "山口银行", R.drawable.wallet_issuer_yamaguchibank, R.drawable.wallet_issuer_yamaguchibank_card, 0xFF6F3859, listOf("山口银行")),
        WalletIssuerLogo("yantaibank", "烟台银行", R.drawable.wallet_issuer_yantaibank, R.drawable.wallet_issuer_yantaibank_card, 0xFF244B6B, listOf("烟台银行")),
        WalletIssuerLogo("z-bank", "武汉众邦银行", R.drawable.wallet_issuer_z_bank, R.drawable.wallet_issuer_z_bank_card, 0xFF394B80, listOf("武汉众邦银行")),
        WalletIssuerLogo("zaozhuangbank", "枣庄银行", R.drawable.wallet_issuer_zaozhuangbank, R.drawable.wallet_issuer_zaozhuangbank_card, 0xFF246977, listOf("枣庄银行")),
        WalletIssuerLogo("zgbank", "自贡银行", R.drawable.wallet_issuer_zgbank, R.drawable.wallet_issuer_zgbank_card, 0xFF6F3859, listOf("自贡银行")),
        WalletIssuerLogo("zhnsb", "珠海农商银行", R.drawable.wallet_issuer_zhnsb, R.drawable.wallet_issuer_zhnsb_card, 0xFF246977, listOf("珠海农商银行")),
        WalletIssuerLogo("zj96596", "浙江农村信用社联合社", R.drawable.wallet_issuer_zj96596, R.drawable.wallet_issuer_zj96596_card, 0xFF6F3859, listOf("浙江农村信用社联合社")),
        WalletIssuerLogo("zjtlcb", "泰隆银行", R.drawable.wallet_issuer_zjtlcb, R.drawable.wallet_issuer_zjtlcb_card, 0xFF6F3859, listOf("泰隆银行")),
        WalletIssuerLogo("zsebank", "中山农商", R.drawable.wallet_issuer_zsebank, R.drawable.wallet_issuer_zsebank_card, 0xFF79412E, listOf("中山农商", "中山农商银行", "中山农村商业银行")),
        WalletIssuerLogo("zxbk", "正信银行", R.drawable.wallet_issuer_zxbk, R.drawable.wallet_issuer_zxbk_card, 0xFF394B80, listOf("正信银行")),
        WalletIssuerLogo("zybank", "中原银行", R.drawable.wallet_issuer_zybank, R.drawable.wallet_issuer_zybank_card, 0xFF6F3859, listOf("中原银行")),
        WalletIssuerLogo("zzbank", "郑州银行", R.drawable.wallet_issuer_zzbank, R.drawable.wallet_issuer_zzbank_card, 0xFF315D52, listOf("郑州银行")),
    )
}
