export const countryData = [
  { value: '中国', englishName: 'China', chineseName: '中国', code: 'CN', aliases: ['cn'] },
  { value: '香港特别行政区', englishName: 'Hong Kong', chineseName: '香港特别行政区', code: 'HK', aliases: ['香港', 'hk'] },
  { value: '澳门特别行政区', englishName: 'Macau', chineseName: '澳门特别行政区', code: 'MO', aliases: ['澳门', 'macao', 'mo'] },
  { value: '台湾', englishName: 'Taiwan of China', chineseName: '台湾', code: 'TW', aliases: ['taiwan', 'tw'] },
  { value: '美国', englishName: 'United States of America', chineseName: '美国', code: 'US', aliases: ['united states', 'usa', 'us'] },
  { value: '英国', englishName: 'United Kingdom of Great Britain and Northern Ireland', chineseName: '英国', code: 'GB', aliases: ['united kingdom', 'uk'] },
  { value: '新加坡', englishName: 'Singapore', chineseName: '新加坡', code: 'SG', aliases: ['sg'] },
  { value: '德国', englishName: 'Germany', chineseName: '德国', code: 'DE', aliases: ['de'] },
  { value: '日本', englishName: 'Japan', chineseName: '日本', code: 'JP', aliases: ['jp'] },
  { value: '韩国', englishName: 'Republic of Korea', chineseName: '韩国', code: 'KR', aliases: ['south korea', 'kr'] },
  { value: '澳大利亚', englishName: 'Australia', chineseName: '澳大利亚', code: 'AU', aliases: ['au'] },
  { value: '加拿大', englishName: 'Canada', chineseName: '加拿大', code: 'CA', aliases: ['ca'] },
  { value: '法国', englishName: 'France', chineseName: '法国', code: 'FR', aliases: ['fr'] },
  { value: '意大利', englishName: 'Italy', chineseName: '意大利', code: 'IT', aliases: ['it'] },
  { value: '西班牙', englishName: 'Spain', chineseName: '西班牙', code: 'ES', aliases: ['es'] },
  { value: '荷兰', englishName: 'Netherlands', chineseName: '荷兰', code: 'NL', aliases: ['nl'] },
  { value: '瑞士', englishName: 'Switzerland', chineseName: '瑞士', code: 'CH', aliases: ['ch'] },
  { value: '泰国', englishName: 'Thailand', chineseName: '泰国', code: 'TH', aliases: ['th'] },
  { value: '马来西亚', englishName: 'Malaysia', chineseName: '马来西亚', code: 'MY', aliases: ['my'] },
  { value: '印度尼西亚', englishName: 'Indonesia', chineseName: '印度尼西亚', code: 'ID', aliases: ['indonesia', 'id'] },
  { value: '菲律宾', englishName: 'Philippines', chineseName: '菲律宾', code: 'PH', aliases: ['ph'] },
  { value: '越南', englishName: 'Vietnam', chineseName: '越南', code: 'VN', aliases: ['vn'] },
  { value: '印度', englishName: 'India', chineseName: '印度', code: 'IN', aliases: ['in'] },
  { value: '巴西', englishName: 'Brazil', chineseName: '巴西', code: 'BR', aliases: ['br'] },
  { value: '阿根廷', englishName: 'Argentina', chineseName: '阿根廷', code: 'AR', aliases: ['ar'] },
  { value: '墨西哥', englishName: 'Mexico', chineseName: '墨西哥', code: 'MX', aliases: ['mx'] },
  { value: '俄罗斯', englishName: 'Russian Federation', chineseName: '俄罗斯', code: 'RU', aliases: ['russia', 'ru'] },
  { value: '南非', englishName: 'South Africa', chineseName: '南非', code: 'ZA', aliases: ['za'] },
  { value: '土耳其', englishName: 'Turkey', chineseName: '土耳其', code: 'TR', aliases: ['tr'] },
  { value: '沙特阿拉伯', englishName: 'Saudi Arabia', chineseName: '沙特阿拉伯', code: 'SA', aliases: ['sa'] },
  { value: '阿联酋', englishName: 'United Arab Emirates', chineseName: '阿联酋', code: 'AE', aliases: ['uae', 'ae'] },
  { value: '以色列', englishName: 'Israel', chineseName: '以色列', code: 'IL', aliases: ['il'] },
  { value: '埃及', englishName: 'Egypt', chineseName: '埃及', code: 'EG', aliases: ['eg'] },
  { value: '新西兰', englishName: 'New Zealand', chineseName: '新西兰', code: 'NZ', aliases: ['nz'] },
]

export const bankList = [
  { value: '工商银行', englishName: 'Industrial and Commercial Bank of China', chineseName: '工商银行', code: 'ICBC', aliases: ['中国工商银行', 'icbc'] },
  { value: '建设银行', englishName: 'China Construction Bank', chineseName: '建设银行', code: 'CCB', aliases: ['中国建设银行', 'ccb'] },
  { value: '农业银行', englishName: 'Agricultural Bank of China', chineseName: '农业银行', code: 'ABC', aliases: ['中国农业银行', 'abc'] },
  { value: '中国银行', englishName: 'Bank of China', chineseName: '中国银行', code: 'BOC', aliases: ['boc'] },
  { value: '交通银行', englishName: 'Bank of Communications', chineseName: '交通银行', code: 'BOCOM', aliases: ['bocom'] },
  { value: '邮储银行', englishName: 'Postal Savings Bank of China', chineseName: '邮储银行', code: 'PSBC', aliases: ['中国邮政储蓄银行', 'psbc'] },
  { value: '招商银行', englishName: 'China Merchants Bank', chineseName: '招商银行', code: 'CMB', aliases: ['cmb'] },
  { value: '中信银行', englishName: 'China CITIC Bank', chineseName: '中信银行', code: 'CITIC', aliases: ['citic'] },
  { value: '光大银行', englishName: 'China Everbright Bank', chineseName: '光大银行', code: 'CEB', aliases: ['ceb'] },
  { value: '华夏银行', englishName: 'Huaxia Bank', chineseName: '华夏银行', code: 'HXBANK', aliases: [] },
  { value: '民生银行', englishName: 'China Minsheng Bank', chineseName: '民生银行', code: 'CMBC', aliases: ['cmbc'] },
  { value: '平安银行', englishName: 'Ping An Bank', chineseName: '平安银行', code: 'PAB', aliases: ['pab'] },
  { value: '兴业银行', englishName: 'Industrial Bank', chineseName: '兴业银行', code: 'CIB', aliases: ['cib'] },
  { value: '浦发银行', englishName: 'Shanghai Pudong Development Bank', chineseName: '浦发银行', code: 'SPDB', aliases: ['spdb'] },
  { value: '广发银行', englishName: 'China Guangfa Bank', chineseName: '广发银行', code: 'CGB', aliases: ['gdb', 'cgb'] },
  { value: '北京银行', englishName: 'Bank of Beijing', chineseName: '北京银行', code: 'BOB', aliases: ['bob'] },
  { value: '宁波银行', englishName: 'Bank of Ningbo', chineseName: '宁波银行', code: 'BON', aliases: [] },
  { value: '江苏银行', englishName: 'Bank of Jiangsu', chineseName: '江苏银行', code: 'BOJS', aliases: [] },
  { value: '汇丰银行', englishName: 'HSBC', chineseName: '汇丰银行', code: 'HSBC', aliases: ['hsbc'] },
  { value: '渣打银行', englishName: 'Standard Chartered Bank', chineseName: '渣打银行', code: 'SCB', aliases: ['standard chartered', 'scb'] },
  { value: '花旗银行', englishName: 'Citibank', chineseName: '花旗银行', code: 'CITI', aliases: ['citi', 'citibank'] },
  { value: '东亚银行', englishName: 'Bank of East Asia', chineseName: '东亚银行', code: 'BEA', aliases: ['bea'] },
  { value: '恒生银行', englishName: 'Hang Seng Bank', chineseName: '恒生银行', code: 'HANGSENG', aliases: [] },
  { value: '星展银行', englishName: 'DBS Bank', chineseName: '星展银行', code: 'DBS', aliases: ['dbs'] },
  { value: '美国银行', englishName: 'Bank of America', chineseName: '美国银行', code: 'BOFA', aliases: ['boa', 'bank of america'] },
  { value: '摩根大通银行', englishName: 'JPMorgan Chase Bank', chineseName: '摩根大通银行', code: 'JPMC', aliases: ['jpmorgan', 'jp morgan', 'chase'] },
  { value: '德意志银行', englishName: 'Deutsche Bank', chineseName: '德意志银行', code: 'DB', aliases: ['deutsche bank'] },
  { value: '华侨银行', englishName: 'OCBC Bank', chineseName: '华侨银行', code: 'OCBC', aliases: ['ocbc'] },
  { value: '众安银行', englishName: 'ZA Bank', chineseName: '众安银行', code: 'ZABANK', aliases: ['za bank'] },
  { value: '招商永隆银行', englishName: 'CMB Wing Lung Bank', chineseName: '招商永隆银行', code: 'WLB', aliases: ['wing lung bank'] },
]

export const cardLevelData = [
  { value: '银联-普卡', englishName: 'UnionPay Classic', chineseName: '银联-普卡', code: 'UNIONPAY_CLASSIC', aliases: ['unionpay classic'] },
  { value: '银联-金卡', englishName: 'UnionPay Gold', chineseName: '银联-金卡', code: 'UNIONPAY_GOLD', aliases: ['unionpay gold'] },
  { value: '银联-白金卡', englishName: 'UnionPay Platinum', chineseName: '银联-白金卡', code: 'UNIONPAY_PLATINUM', aliases: ['unionpay platinum'] },
  { value: '银联-钻石卡', englishName: 'UnionPay Diamond', chineseName: '银联-钻石卡', code: 'UNIONPAY_DIAMOND', aliases: ['unionpay diamond'] },
  { value: '银联-黑钻卡', englishName: 'UnionPay Black Diamond', chineseName: '银联-黑钻卡', code: 'UNIONPAY_BLACK_DIAMOND', aliases: [] },
  { value: '银联 + VISA', englishName: 'UnionPay + VISA', chineseName: '银联 + VISA', code: 'UNIONPAY_VISA', aliases: [] },
  { value: '银联 + MasterCard', englishName: 'UnionPay + MasterCard', chineseName: '银联 + MasterCard', code: 'UNIONPAY_MASTERCARD', aliases: [] },
  { value: '银联 + JCB', englishName: 'UnionPay + JCB', chineseName: '银联 + JCB', code: 'UNIONPAY_JCB', aliases: [] },
  { value: '银联 + AE', englishName: 'UnionPay + American Express', chineseName: '银联 + AE', code: 'UNIONPAY_AE', aliases: [] },
  { value: 'VISA-普卡', englishName: 'VISA Classic', chineseName: 'VISA-普卡', code: 'VISA_CLASSIC', aliases: ['visa classic'] },
  { value: 'VISA-金卡', englishName: 'VISA Gold', chineseName: 'VISA-金卡', code: 'VISA_GOLD', aliases: ['visa gold'] },
  { value: 'VISA-白金卡', englishName: 'VISA Platinum', chineseName: 'VISA-白金卡', code: 'VISA_PLATINUM', aliases: ['visa platinum'] },
  { value: 'VISA-御玺卡', englishName: 'VISA Signature', chineseName: 'VISA-御玺卡', code: 'VISA_SIGNATURE', aliases: ['visa signature'] },
  { value: 'VISA-无限卡', englishName: 'VISA Infinite', chineseName: 'VISA-无限卡', code: 'VISA_INFINITE', aliases: ['visa infinite'] },
  { value: 'MasterCard-普卡', englishName: 'MasterCard Classic', chineseName: 'MasterCard-普卡', code: 'MC_CLASSIC', aliases: ['mastercard classic'] },
  { value: 'MasterCard-金卡', englishName: 'MasterCard Gold', chineseName: 'MasterCard-金卡', code: 'MC_GOLD', aliases: ['mastercard gold'] },
  { value: 'MasterCard-白金卡', englishName: 'MasterCard Platinum', chineseName: 'MasterCard-白金卡', code: 'MC_PLATINUM', aliases: ['mastercard platinum'] },
  { value: 'MasterCard-钛金卡', englishName: 'MasterCard Titanium', chineseName: 'MasterCard-钛金卡', code: 'MC_TITANIUM', aliases: ['mastercard titanium'] },
  { value: 'MasterCard-世界卡', englishName: 'MasterCard World', chineseName: 'MasterCard-世界卡', code: 'MC_WORLD', aliases: ['mastercard world'] },
  { value: 'MasterCard-世界之极卡', englishName: 'MasterCard World Elite', chineseName: 'MasterCard-世界之极卡', code: 'MC_WORLD_ELITE', aliases: ['mastercard world elite'] },
  { value: 'JCB-普卡', englishName: 'JCB Classic', chineseName: 'JCB-普卡', code: 'JCB_CLASSIC', aliases: ['jcb classic'] },
  { value: 'JCB-金卡', englishName: 'JCB Gold', chineseName: 'JCB-金卡', code: 'JCB_GOLD', aliases: ['jcb gold'] },
  { value: 'JCB-白金卡', englishName: 'JCB Platinum', chineseName: 'JCB-白金卡', code: 'JCB_PLATINUM', aliases: ['jcb platinum'] },
  { value: 'JCB-御尊卡', englishName: 'JCB Prestige', chineseName: 'JCB-御尊卡', code: 'JCB_PRESTIGE', aliases: [] },
  { value: 'AE-经典-绿卡', englishName: 'American Express Green', chineseName: 'AE-经典-绿卡', code: 'AE_GREEN', aliases: ['amex green'] },
  { value: 'AE-经典-红卡', englishName: 'American Express Red', chineseName: 'AE-经典-红卡', code: 'AE_RED', aliases: [] },
  { value: 'AE-经典-金卡', englishName: 'American Express Gold', chineseName: 'AE-经典-金卡', code: 'AE_GOLD', aliases: ['amex gold'] },
  { value: 'AE-经典-蓝卡', englishName: 'American Express Blue', chineseName: 'AE-经典-蓝卡', code: 'AE_BLUE', aliases: [] },
  { value: 'AE-经典-新贵白金卡', englishName: 'American Express Platinum Credit', chineseName: 'AE-经典-新贵白金卡', code: 'AE_PLATINUM_CREDIT', aliases: [] },
  { value: 'AE-经典-clear卡', englishName: 'American Express Clear', chineseName: 'AE-经典-clear卡', code: 'AE_CLEAR', aliases: [] },
  { value: 'AE-经典-Explorer卡', englishName: 'American Express Explorer', chineseName: 'AE-经典-Explorer卡', code: 'AE_EXPLORER', aliases: [] },
  { value: 'AE-经典-Cash Magnet卡', englishName: 'American Express Cash Magnet', chineseName: 'AE-经典-Cash Magnet卡', code: 'AE_CASH_MAGNET', aliases: [] },
  { value: 'AE-经典-百夫长白金卡', englishName: 'American Express Centurion Platinum', chineseName: 'AE-经典-百夫长白金卡', code: 'AE_CENTURION_PLATINUM', aliases: [] },
  { value: 'AE-经典-百夫长黑金卡', englishName: 'American Express Centurion Black', chineseName: 'AE-经典-百夫长黑金卡', code: 'AE_CENTURION_BLACK', aliases: [] },
  { value: 'AE-蓝盒子-MEMBER卡', englishName: 'American Express Blue Box Member', chineseName: 'AE-蓝盒子-MEMBER卡', code: 'AE_BLUEBOX_MEMBER', aliases: [] },
  { value: 'AE-蓝盒子-SELECT卡', englishName: 'American Express Blue Box Select', chineseName: 'AE-蓝盒子-SELECT卡', code: 'AE_BLUEBOX_SELECT', aliases: [] },
  { value: 'AE-蓝盒子-MAX卡', englishName: 'American Express Blue Box Max', chineseName: 'AE-蓝盒子-MAX卡', code: 'AE_BLUEBOX_MAX', aliases: [] },
  { value: 'AE-蓝盒子-ICON卡', englishName: 'American Express Blue Box Icon', chineseName: 'AE-蓝盒子-ICON卡', code: 'AE_BLUEBOX_ICON', aliases: [] },
]

export const currencyData = [
  { value: 'CNY', englishName: 'Chinese Yuan', chineseName: '人民币', code: 'CNY', symbol: '¥', aliases: ['rmb', 'renminbi'] },
  { value: 'CNH', englishName: 'Chinese Yuan Offshore', chineseName: '人民币离岸', code: 'CNH', symbol: 'CNH', aliases: [] },
  { value: 'USD', englishName: 'US Dollar', chineseName: '美元', code: 'USD', symbol: '$', aliases: ['usdollar'] },
  { value: 'EUR', englishName: 'Euro', chineseName: '欧元', code: 'EUR', symbol: '€', aliases: [] },
  { value: 'GBP', englishName: 'British Pound', chineseName: '英镑', code: 'GBP', symbol: '£', aliases: [] },
  { value: 'JPY', englishName: 'Japanese Yen', chineseName: '日元', code: 'JPY', symbol: '¥', aliases: [] },
  { value: 'HKD', englishName: 'Hong Kong Dollar', chineseName: '港币', code: 'HKD', symbol: 'HK$', aliases: [] },
  { value: 'MOP', englishName: 'Macanese Pataca', chineseName: '澳门币', code: 'MOP', symbol: 'MOP$', aliases: [] },
  { value: 'TWD', englishName: 'New Taiwan Dollar', chineseName: '新台币', code: 'TWD', symbol: 'NT$', aliases: [] },
  { value: 'SGD', englishName: 'Singapore Dollar', chineseName: '新加坡元', code: 'SGD', symbol: 'S$', aliases: [] },
  { value: 'AUD', englishName: 'Australian Dollar', chineseName: '澳元', code: 'AUD', symbol: 'A$', aliases: [] },
  { value: 'CAD', englishName: 'Canadian Dollar', chineseName: '加元', code: 'CAD', symbol: 'C$', aliases: [] },
  { value: 'CHF', englishName: 'Swiss Franc', chineseName: '瑞士法郎', code: 'CHF', symbol: 'CHF', aliases: [] },
  { value: 'SEK', englishName: 'Swedish Krona', chineseName: '瑞典克朗', code: 'SEK', symbol: 'SEK', aliases: [] },
  { value: 'DKK', englishName: 'Danish Krone', chineseName: '丹麦克朗', code: 'DKK', symbol: 'DKK', aliases: [] },
  { value: 'NOK', englishName: 'Norwegian Krone', chineseName: '挪威克朗', code: 'NOK', symbol: 'NOK', aliases: [] },
  { value: 'NZD', englishName: 'New Zealand Dollar', chineseName: '新西兰元', code: 'NZD', symbol: 'NZ$', aliases: [] },
  { value: 'KRW', englishName: 'Korean Won', chineseName: '韩元', code: 'KRW', symbol: 'KRW', aliases: [] },
  { value: 'THB', englishName: 'Thai Baht', chineseName: '泰铢', code: 'THB', symbol: '฿', aliases: [] },
  { value: 'MYR', englishName: 'Malaysian Ringgit', chineseName: '马来西亚林吉特', code: 'MYR', symbol: 'MYR', aliases: [] },
  { value: 'IDR', englishName: 'Indonesian Rupiah', chineseName: '印尼卢比', code: 'IDR', symbol: 'IDR', aliases: ['indonesian rupiah'] },
  { value: 'VND', englishName: 'Vietnamese Dong', chineseName: '越南盾', code: 'VND', symbol: 'VND', aliases: [] },
  { value: 'PHP', englishName: 'Philippine Peso', chineseName: '菲律宾比索', code: 'PHP', symbol: 'PHP', aliases: [] },
  { value: 'INR', englishName: 'Indian Rupee', chineseName: '印度卢比', code: 'INR', symbol: 'INR', aliases: [] },
]

export const qualificationStatusData = [
  { value: '1', englishName: 'Qualified', chineseName: '已达标', code: 'QUALIFIED', aliases: [] },
  { value: '2', englishName: 'Not Qualified', chineseName: '未达标', code: 'NOT_QUALIFIED', aliases: [] },
  { value: '3', englishName: 'Lifetime Fee Waived', chineseName: '终免年费', code: 'LIFETIME_WAIVED', aliases: ['fee waived forever'] },
]
