export const countryData = [
  { value: '中国', englishName: 'China', chineseName: '中国', code: 'CN', aliases: ['cn'] },
  { value: '香港特别行政区', englishName: 'Hong Kong', chineseName: '香港特别行政区', code: 'HK', aliases: ['香港', 'hk'] },
  { value: '澳门特别行政区', englishName: 'Macau', chineseName: '澳门特别行政区', code: 'MO', aliases: ['澳门', 'macao', 'mo'] },
  { value: '台湾', englishName: 'Taiwan of China', chineseName: '台湾', code: 'TW', aliases: ['taiwan', 'tw'] },
  { value: '美国', englishName: 'United States of America', chineseName: '美国', code: 'US', aliases: ['united states', 'usa', 'us'] },
  { value: '英国', englishName: 'United Kingdom of Great Britain and Northern Ireland', chineseName: '英国', code: 'GB', aliases: ['united kingdom', 'uk'] },
  { value: '新加坡', englishName: 'Singapore', chineseName: '新加坡', code: 'SG', aliases: ['sg'] },
  { value: '德国', englishName: 'Germany', chineseName: '德国', code: 'DE', aliases: ['de'] },
  { value: '日本', englishName: 'Japan', chineseName: '日本', code: 'JP', aliases: ['jp'] },
  { value: '韩国', englishName: 'Republic of Korea', chineseName: '韩国', code: 'KR', aliases: ['south korea', 'kr'] },
  { value: '澳大利亚', englishName: 'Australia', chineseName: '澳大利亚', code: 'AU', aliases: ['au'] },
  { value: '加拿大', englishName: 'Canada', chineseName: '加拿大', code: 'CA', aliases: ['ca'] },
  { value: '法国', englishName: 'France', chineseName: '法国', code: 'FR', aliases: ['fr'] },
  { value: '意大利', englishName: 'Italy', chineseName: '意大利', code: 'IT', aliases: ['it'] },
  { value: '西班牙', englishName: 'Spain', chineseName: '西班牙', code: 'ES', aliases: ['es'] },
  { value: '荷兰', englishName: 'Netherlands', chineseName: '荷兰', code: 'NL', aliases: ['nl'] },
  { value: '瑞士', englishName: 'Switzerland', chineseName: '瑞士', code: 'CH', aliases: ['ch'] },
  { value: '泰国', englishName: 'Thailand', chineseName: '泰国', code: 'TH', aliases: ['th'] },
  { value: '马来西亚', englishName: 'Malaysia', chineseName: '马来西亚', code: 'MY', aliases: ['my'] },
  { value: '印度尼西亚', englishName: 'Indonesia', chineseName: '印度尼西亚', code: 'ID', aliases: ['indonesia', 'id'] },
  { value: '菲律宾', englishName: 'Philippines', chineseName: '菲律宾', code: 'PH', aliases: ['ph'] },
  { value: '越南', englishName: 'Vietnam', chineseName: '越南', code: 'VN', aliases: ['vn'] },
  { value: '印度', englishName: 'India', chineseName: '印度', code: 'IN', aliases: ['in'] },
  { value: '巴西', englishName: 'Brazil', chineseName: '巴西', code: 'BR', aliases: ['br'] },
  { value: '阿根廷', englishName: 'Argentina', chineseName: '阿根廷', code: 'AR', aliases: ['ar'] },
  { value: '墨西哥', englishName: 'Mexico', chineseName: '墨西哥', code: 'MX', aliases: ['mx'] },
  { value: '俄罗斯', englishName: 'Russian Federation', chineseName: '俄罗斯', code: 'RU', aliases: ['russia', 'ru'] },
  { value: '南非', englishName: 'South Africa', chineseName: '南非', code: 'ZA', aliases: ['za'] },
  { value: '土耳其', englishName: 'Turkey', chineseName: '土耳其', code: 'TR', aliases: ['tr'] },
  { value: '沙特阿拉伯', englishName: 'Saudi Arabia', chineseName: '沙特阿拉伯', code: 'SA', aliases: ['sa'] },
  { value: '阿联酋', englishName: 'United Arab Emirates', chineseName: '阿联酋', code: 'AE', aliases: ['uae', 'ae'] },
  { value: '以色列', englishName: 'Israel', chineseName: '以色列', code: 'IL', aliases: ['il'] },
  { value: '埃及', englishName: 'Egypt', chineseName: '埃及', code: 'EG', aliases: ['eg'] },
  { value: '新西兰', englishName: 'New Zealand', chineseName: '新西兰', code: 'NZ', aliases: ['nz'] },
]

const createBank = (value, englishName, code, aliases = []) => ({
  value,
  englishName,
  chineseName: value,
  code,
  aliases,
})

export const bankList = [
  // 中国内地
  createBank('工商银行', 'Industrial and Commercial Bank of China', 'ICBC', ['中国工商银行', 'icbc']),
  createBank('建设银行', 'China Construction Bank', 'CCB', ['中国建设银行', 'ccb']),
  createBank('农业银行', 'Agricultural Bank of China', 'ABC', ['中国农业银行', 'abc']),
  createBank('中国银行', 'Bank of China', 'BOC', ['boc']),
  createBank('交通银行', 'Bank of Communications', 'BOCOM', ['bocom']),
  createBank('邮储银行', 'Postal Savings Bank of China', 'PSBC', ['中国邮政储蓄银行', 'psbc']),
  createBank('招商银行', 'China Merchants Bank', 'CMB', ['cmb']),
  createBank('中信银行', 'China CITIC Bank', 'CITIC', ['citic']),
  createBank('光大银行', 'China Everbright Bank', 'CEB', ['ceb']),
  createBank('华夏银行', 'Huaxia Bank', 'HXBANK'),
  createBank('民生银行', 'China Minsheng Bank', 'CMBC', ['cmbc']),
  createBank('平安银行', 'Ping An Bank', 'PAB'),
  createBank('兴业银行', 'Industrial Bank', 'CIB'),
  createBank('浦发银行', 'Shanghai Pudong Development Bank', 'SPDB', ['spdb']),
  createBank('广发银行', 'China Guangfa Bank', 'CGB', ['gdb', 'cgb']),
  createBank('北京银行', 'Bank of Beijing', 'BOB'),
  createBank('上海银行', 'Bank of Shanghai', 'BOS'),
  createBank('江苏银行', 'Bank of Jiangsu', 'BOJS'),
  createBank('宁波银行', 'Bank of Ningbo', 'BON'),
  createBank('南京银行', 'Bank of Nanjing', 'BONJ'),
  createBank('杭州银行', 'Bank of Hangzhou', 'BOHZ'),
  createBank('成都银行', 'Bank of Chengdu', 'BOCD'),
  createBank('重庆银行', 'Bank of Chongqing', 'BOCQ'),
  createBank('徽商银行', 'Huishang Bank', 'HSBANK'),
  createBank('浙商银行', 'China Zheshang Bank', 'CZBANK'),
  createBank('渤海银行', 'China Bohai Bank', 'CBHB'),
  createBank('上海农商银行', 'Shanghai Rural Commercial Bank', 'SHRCB'),
  createBank('重庆农商银行', 'Chongqing Rural Commercial Bank', 'CQRCB'),
  createBank('微众银行', 'WeBank', 'WEBANK'),
  createBank('网商银行', 'MYbank', 'MYBANK'),

  // 中国港澳台
  createBank('汇丰银行', 'HSBC', 'HSBC', ['hsbc']),
  createBank('恒生银行', 'Hang Seng Bank', 'HANGSENG'),
  createBank('中银香港', 'Bank of China Hong Kong', 'BOCHK', ['中国银行香港']),
  createBank('渣打银行', 'Standard Chartered Bank', 'SCB', ['standard chartered', 'scb']),
  createBank('东亚银行', 'Bank of East Asia', 'BEA', ['bea']),
  createBank('花旗银行', 'Citibank', 'CITI', ['citi', 'citibank']),
  createBank('星展银行', 'DBS Bank', 'DBS', ['dbs']),
  createBank('华侨银行', 'OCBC Bank', 'OCBC', ['ocbc']),
  createBank('众安银行', 'ZA Bank', 'ZABANK', ['za bank']),
  createBank('招商永隆银行', 'CMB Wing Lung Bank', 'WLB', ['wing lung bank']),
  createBank('Mox Bank', 'Mox Bank', 'MOX'),
  createBank('大西洋银行', 'Banco Nacional Ultramarino', 'BNU'),
  createBank('澳门商业银行', 'Banco Comercial de Macau', 'BCM'),
  createBank('大丰银行', 'Tai Fung Bank', 'TFB'),
  createBank('澳门国际银行', 'Luso International Banking', 'LIB'),
  createBank('中国信托银行', 'CTBC Bank', 'CTBC', ['中信银行台湾']),
  createBank('国泰世华银行', 'Cathay United Bank', 'CUB'),
  createBank('兆丰国际商业银行', 'Mega International Commercial Bank', 'MEGA'),
  createBank('台北富邦银行', 'Taipei Fubon Bank', 'TFB-TW'),
  createBank('玉山银行', 'E.SUN Bank', 'ESUN'),
  createBank('台新银行', 'Taishin International Bank', 'TAISHIN'),
  createBank('台湾银行', 'Bank of Taiwan', 'BOT'),
  createBank('第一银行', 'First Commercial Bank', 'FCB-TW'),
  createBank('华南银行', 'Hua Nan Commercial Bank', 'HNCB'),
  createBank('合作金库银行', 'Taiwan Cooperative Bank', 'TCB'),

  // 北美
  createBank('摩根大通银行', 'JPMorgan Chase Bank', 'JPMC', ['jpmorgan', 'jp morgan', 'chase']),
  createBank('美国银行', 'Bank of America', 'BOFA', ['boa', 'bank of america']),
  createBank('富国银行', 'Wells Fargo', 'WELLSFARGO'),
  createBank('U.S. Bank', 'U.S. Bank', 'USBANK'),
  createBank('Capital One', 'Capital One', 'CAPITALONE'),
  createBank('PNC Bank', 'PNC Bank', 'PNC'),
  createBank('Truist Bank', 'Truist Bank', 'TRUIST'),
  createBank('美国运通', 'American Express', 'AMEX', ['amex']),
  createBank('Discover Bank', 'Discover Bank', 'DISCOVER'),
  createBank('加拿大皇家银行', 'Royal Bank of Canada', 'RBC', ['rbc']),
  createBank('TD Bank', 'Toronto-Dominion Bank', 'TD', ['td bank']),
  createBank('加拿大丰业银行', 'Scotiabank', 'SCOTIA'),
  createBank('蒙特利尔银行', 'Bank of Montreal', 'BMO', ['bmo']),
  createBank('加拿大帝国商业银行', 'Canadian Imperial Bank of Commerce', 'CIBC', ['cibc']),
  createBank('加拿大国民银行', 'National Bank of Canada', 'NBC'),
  createBank('Desjardins', 'Desjardins Group', 'DESJARDINS'),

  // 英国及欧洲
  createBank('巴克莱银行', 'Barclays', 'BARCLAYS'),
  createBank('Lloyds Bank', 'Lloyds Bank', 'LLOYDS'),
  createBank('NatWest', 'NatWest', 'NATWEST'),
  createBank('Santander UK', 'Santander UK', 'SANTANDER-UK'),
  createBank('Nationwide Building Society', 'Nationwide Building Society', 'NATIONWIDE'),
  createBank('Halifax', 'Halifax', 'HALIFAX'),
  createBank('Monzo Bank', 'Monzo Bank', 'MONZO'),
  createBank('Starling Bank', 'Starling Bank', 'STARLING'),
  createBank('德意志银行', 'Deutsche Bank', 'DB', ['deutsche bank']),
  createBank('德国商业银行', 'Commerzbank', 'COMMERZBANK'),
  createBank('Sparkasse', 'Sparkasse', 'SPARKASSE'),
  createBank('ING Germany', 'ING Germany', 'ING-DE'),
  createBank('Deutsche Kreditbank', 'Deutsche Kreditbank', 'DKB', ['dkb']),
  createBank('HypoVereinsbank', 'HypoVereinsbank', 'HVB'),
  createBank('N26 Bank', 'N26 Bank', 'N26'),
  createBank('法国巴黎银行', 'BNP Paribas', 'BNPP'),
  createBank('法国农业信贷银行', 'Credit Agricole', 'CA-FR'),
  createBank('法国兴业银行', 'Societe Generale', 'SG-FR'),
  createBank('Groupe BPCE', 'Groupe BPCE', 'BPCE'),
  createBank('Crédit Mutuel', 'Credit Mutuel', 'CM-FR'),
  createBank('La Banque Postale', 'La Banque Postale', 'LBP'),
  createBank('裕信银行', 'UniCredit', 'UNICREDIT'),
  createBank('联合圣保罗银行', 'Intesa Sanpaolo', 'INTESA'),
  createBank('Banco BPM', 'Banco BPM', 'BPM'),
  createBank('Banca Monte dei Paschi di Siena', 'Banca Monte dei Paschi di Siena', 'MPS'),
  createBank('桑坦德银行', 'Banco Santander', 'SANTANDER'),
  createBank('西班牙对外银行', 'BBVA', 'BBVA'),
  createBank('CaixaBank', 'CaixaBank', 'CAIXA'),
  createBank('Banco Sabadell', 'Banco Sabadell', 'SABADELL'),
  createBank('Bankinter', 'Bankinter', 'BANKINTER'),
  createBank('ING Bank', 'ING Bank', 'ING'),
  createBank('荷兰合作银行', 'Rabobank', 'RABOBANK'),
  createBank('荷兰银行', 'ABN AMRO', 'ABNAMRO'),
  createBank('bunq', 'Bunq', 'BUNQ'),
  createBank('瑞银', 'UBS', 'UBS'),
  createBank('Raiffeisen Switzerland', 'Raiffeisen Switzerland', 'RAIFFEISEN-CH'),
  createBank('Zürcher Kantonalbank', 'Zurcher Kantonalbank', 'ZKB'),
  createBank('PostFinance', 'PostFinance', 'POSTFINANCE'),
  createBank('瑞士宝盛银行', 'Julius Baer', 'JULIUSBAER'),

  // 东亚及大洋洲
  createBank('三菱日联银行', 'MUFG Bank', 'MUFG'),
  createBank('三井住友银行', 'Sumitomo Mitsui Banking Corporation', 'SMBC'),
  createBank('瑞穗银行', 'Mizuho Bank', 'MIZUHO'),
  createBank('日本邮政银行', 'Japan Post Bank', 'JPBANK'),
  createBank('Resona Bank', 'Resona Bank', 'RESONA'),
  createBank('Rakuten Bank', 'Rakuten Bank', 'RAKUTEN'),
  createBank('SBI Sumishin Net Bank', 'SBI Sumishin Net Bank', 'SSNB'),
  createBank('Sony Bank', 'Sony Bank', 'SONYBANK'),
  createBank('KB国民银行', 'KB Kookmin Bank', 'KB'),
  createBank('新韩银行', 'Shinhan Bank', 'SHINHAN'),
  createBank('韩亚银行', 'Hana Bank', 'HANA'),
  createBank('友利银行', 'Woori Bank', 'WOORI'),
  createBank('NH NongHyup Bank', 'NH NongHyup Bank', 'NH'),
  createBank('IBK Industrial Bank of Korea', 'Industrial Bank of Korea', 'IBK'),
  createBank('KakaoBank', 'KakaoBank', 'KAKAO'),
  createBank('Toss Bank', 'Toss Bank', 'TOSS'),
  createBank('澳大利亚联邦银行', 'Commonwealth Bank of Australia', 'CBA'),
  createBank('西太平洋银行', 'Westpac', 'WESTPAC'),
  createBank('澳大利亚国民银行', 'National Australia Bank', 'NAB'),
  createBank('澳新银行', 'Australia and New Zealand Banking Group', 'ANZ'),
  createBank('麦格理银行', 'Macquarie Bank', 'MACQUARIE'),
  createBank('Bendigo and Adelaide Bank', 'Bendigo and Adelaide Bank', 'BENDIGO'),
  createBank('Bank of New Zealand', 'Bank of New Zealand', 'BNZ'),
  createBank('Kiwibank', 'Kiwibank', 'KIWIBANK'),
  createBank('ASB Bank', 'ASB Bank', 'ASB'),
  createBank('TSB New Zealand', 'TSB Bank New Zealand', 'TSB-NZ'),

  // 东南亚及印度
  createBank('大华银行', 'United Overseas Bank', 'UOB', ['uob']),
  createBank('马来亚银行', 'Maybank', 'MAYBANK'),
  createBank('联昌国际银行', 'CIMB Bank', 'CIMB'),
  createBank('大众银行', 'Public Bank Berhad', 'PBB'),
  createBank('兴业银行（马来西亚）', 'RHB Bank', 'RHB'),
  createBank('丰隆银行', 'Hong Leong Bank', 'HLB'),
  createBank('Alliance Bank Malaysia', 'Alliance Bank Malaysia', 'ALLIANCE-MY'),
  createBank('盘谷银行', 'Bangkok Bank', 'BBL'),
  createBank('开泰银行', 'Kasikornbank', 'KBANK'),
  createBank('Siam Commercial Bank', 'Siam Commercial Bank', 'SCB-TH'),
  createBank('Krungthai Bank', 'Krung Thai Bank', 'KTB'),
  createBank('Krungsri', 'Bank of Ayudhya', 'KRUNGSRI'),
  createBank('ttb bank', 'TMBThanachart Bank', 'TTB'),
  createBank('Bank Mandiri', 'Bank Mandiri', 'MANDIRI'),
  createBank('Bank Rakyat Indonesia', 'Bank Rakyat Indonesia', 'BRI'),
  createBank('Bank Central Asia', 'Bank Central Asia', 'BCA'),
  createBank('Bank Negara Indonesia', 'Bank Negara Indonesia', 'BNI'),
  createBank('Bank Syariah Indonesia', 'Bank Syariah Indonesia', 'BSI'),
  createBank('Bank Tabungan Negara', 'Bank Tabungan Negara', 'BTN'),
  createBank('BDO Unibank', 'BDO Unibank', 'BDO'),
  createBank('Bank of the Philippine Islands', 'Bank of the Philippine Islands', 'BPI'),
  createBank('Metrobank', 'Metropolitan Bank and Trust Company', 'METROBANK'),
  createBank('Land Bank of the Philippines', 'Land Bank of the Philippines', 'LANDBANK'),
  createBank('Philippine National Bank', 'Philippine National Bank', 'PNB'),
  createBank('UnionBank of the Philippines', 'UnionBank of the Philippines', 'UNIONBANK-PH'),
  createBank('Security Bank', 'Security Bank', 'SECURITYBANK'),
  createBank('Vietcombank', 'Vietcombank', 'VCB'),
  createBank('BIDV', 'BIDV', 'BIDV'),
  createBank('VietinBank', 'VietinBank', 'VIETINBANK'),
  createBank('Agribank', 'Agribank Vietnam', 'AGRIBANK-VN'),
  createBank('Techcombank', 'Techcombank', 'TECHCOMBANK'),
  createBank('MB Bank', 'MB Bank', 'MBB'),
  createBank('VPBank', 'VPBank', 'VPBANK'),
  createBank('Asia Commercial Bank', 'Asia Commercial Bank', 'ACB'),
  createBank('State Bank of India', 'State Bank of India', 'SBI'),
  createBank('HDFC Bank', 'HDFC Bank', 'HDFC'),
  createBank('ICICI Bank', 'ICICI Bank', 'ICICI'),
  createBank('Axis Bank', 'Axis Bank', 'AXIS'),
  createBank('Kotak Mahindra Bank', 'Kotak Mahindra Bank', 'KOTAK'),
  createBank('Punjab National Bank', 'Punjab National Bank', 'PNB-IN'),
  createBank('Bank of Baroda', 'Bank of Baroda', 'BOB-IN'),
  createBank('Canara Bank', 'Canara Bank', 'CANARA'),

  // 拉丁美洲
  createBank('Itaú Unibanco', 'Itau Unibanco', 'ITAU'),
  createBank('Banco do Brasil', 'Banco do Brasil', 'BB'),
  createBank('Bradesco', 'Banco Bradesco', 'BRADESCO'),
  createBank('Caixa Econômica Federal', 'Caixa Economica Federal', 'CAIXA-BR'),
  createBank('Santander Brasil', 'Santander Brasil', 'SANTANDER-BR'),
  createBank('Nubank', 'Nubank', 'NUBANK'),
  createBank('BTG Pactual', 'BTG Pactual', 'BTG'),
  createBank('Banco Nación', 'Banco de la Nacion Argentina', 'BNA'),
  createBank('Banco Galicia', 'Banco Galicia', 'GALICIA'),
  createBank('Santander Argentina', 'Santander Argentina', 'SANTANDER-AR'),
  createBank('BBVA Argentina', 'BBVA Argentina', 'BBVA-AR'),
  createBank('Banco Macro', 'Banco Macro', 'MACRO'),
  createBank('BBVA México', 'BBVA Mexico', 'BBVA-MX'),
  createBank('Banorte', 'Banorte', 'BANORTE'),
  createBank('Santander México', 'Santander Mexico', 'SANTANDER-MX'),
  createBank('Banamex', 'Banamex', 'BANAMEX'),
  createBank('HSBC México', 'HSBC Mexico', 'HSBC-MX'),
  createBank('Scotiabank México', 'Scotiabank Mexico', 'SCOTIA-MX'),
  createBank('Banco Inbursa', 'Banco Inbursa', 'INBURSA'),

  // 俄罗斯、非洲及中东
  createBank('Sberbank', 'Sberbank', 'SBER'),
  createBank('VTB Bank', 'VTB Bank', 'VTB'),
  createBank('Gazprombank', 'Gazprombank', 'GAZPROMBANK'),
  createBank('Alfa-Bank', 'Alfa-Bank', 'ALFABANK'),
  createBank('Rosselkhozbank', 'Rosselkhozbank', 'RSHB'),
  createBank('T-Bank', 'T-Bank', 'TBANK'),
  createBank('Sovcombank', 'Sovcombank', 'SOVCOMBANK'),
  createBank('Standard Bank', 'Standard Bank', 'STANDARD-ZA'),
  createBank('FirstRand Bank', 'FirstRand Bank', 'FIRSTRAND', ['fnb']),
  createBank('Absa Bank', 'Absa Bank', 'ABSA'),
  createBank('Nedbank', 'Nedbank', 'NEDBANK'),
  createBank('Capitec Bank', 'Capitec Bank', 'CAPITEC'),
  createBank('Investec Bank', 'Investec Bank', 'INVESTEC'),
  createBank('Ziraat Bank', 'Ziraat Bank', 'ZIRAAT'),
  createBank('Türkiye İş Bankası', 'Isbank', 'ISBANK'),
  createBank('Garanti BBVA', 'Garanti BBVA', 'GARANTI'),
  createBank('Akbank', 'Akbank', 'AKBANK'),
  createBank('Halkbank', 'Halkbank', 'HALKBANK'),
  createBank('VakıfBank', 'VakifBank', 'VAKIFBANK'),
  createBank('Yapı Kredi', 'Yapi Kredi', 'YAPIKREDI'),
  createBank('Saudi National Bank', 'Saudi National Bank', 'SNB'),
  createBank('Al Rajhi Bank', 'Al Rajhi Bank', 'ALRAJHI'),
  createBank('Riyad Bank', 'Riyad Bank', 'RIYAD'),
  createBank('Saudi Awwal Bank', 'Saudi Awwal Bank', 'SAB'),
  createBank('Saudi Investment Bank', 'Saudi Investment Bank', 'SAIB'),
  createBank('Banque Saudi Fransi', 'Banque Saudi Fransi', 'BSF'),
  createBank('First Abu Dhabi Bank', 'First Abu Dhabi Bank', 'FAB'),
  createBank('Emirates NBD', 'Emirates NBD', 'ENBD'),
  createBank('Abu Dhabi Commercial Bank', 'Abu Dhabi Commercial Bank', 'ADCB'),
  createBank('Mashreq', 'Mashreq Bank', 'MASHREQ'),
  createBank('Dubai Islamic Bank', 'Dubai Islamic Bank', 'DIB'),
  createBank('Abu Dhabi Islamic Bank', 'Abu Dhabi Islamic Bank', 'ADIB'),
  createBank('RAKBANK', 'RAKBANK', 'RAKBANK'),
  createBank('Bank Hapoalim', 'Bank Hapoalim', 'HAPOALIM'),
  createBank('Bank Leumi', 'Bank Leumi', 'LEUMI'),
  createBank('Mizrahi-Tefahot Bank', 'Mizrahi-Tefahot Bank', 'MIZRAHI'),
  createBank('Israel Discount Bank', 'Israel Discount Bank', 'DISCOUNT-IL'),
  createBank('First International Bank of Israel', 'First International Bank of Israel', 'FIBI'),
  createBank('National Bank of Egypt', 'National Bank of Egypt', 'NBE'),
  createBank('Banque Misr', 'Banque Misr', 'BANQUEMISR'),
  createBank('Commercial International Bank', 'Commercial International Bank Egypt', 'CIB-EG'),
  createBank('QNB Alahli', 'QNB Alahli', 'QNB-EG'),
  createBank('Banque du Caire', 'Banque du Caire', 'BDC-EG'),
  createBank('Arab African International Bank', 'Arab African International Bank', 'AAIB'),
]

export const cardLevelGroups = [
  {
    value: '银联',
    englishName: 'UnionPay',
    levels: [
      { value: '普卡', englishName: 'Classic', code: 'UNIONPAY_CLASSIC' },
      { value: '金卡', englishName: 'Gold', code: 'UNIONPAY_GOLD' },
      { value: '白金卡', englishName: 'Platinum', code: 'UNIONPAY_PLATINUM' },
      { value: '钻石卡', englishName: 'Diamond', code: 'UNIONPAY_DIAMOND' },
      { value: '黑钻卡', englishName: 'Black Diamond', code: 'UNIONPAY_BLACK_DIAMOND' },
    ],
  },
  {
    value: 'Visa',
    englishName: 'Visa',
    levels: [
      { value: '普卡', englishName: 'Classic', code: 'VISA_CLASSIC' },
      { value: '金卡', englishName: 'Gold', code: 'VISA_GOLD' },
      { value: '白金卡', englishName: 'Platinum', code: 'VISA_PLATINUM' },
      { value: '御玺卡', englishName: 'Signature', code: 'VISA_SIGNATURE' },
      { value: '无限卡', englishName: 'Infinite', code: 'VISA_INFINITE' },
    ],
  },
  {
    value: '万事达',
    englishName: 'Mastercard',
    levels: [
      { value: '普卡', englishName: 'Classic', code: 'MASTERCARD_CLASSIC' },
      { value: '金卡', englishName: 'Gold', code: 'MASTERCARD_GOLD' },
      { value: '白金卡', englishName: 'Platinum', code: 'MASTERCARD_PLATINUM' },
      { value: '钛金卡', englishName: 'Titanium', code: 'MASTERCARD_TITANIUM' },
      { value: '世界卡', englishName: 'World', code: 'MASTERCARD_WORLD' },
      { value: '世界之极卡', englishName: 'World Elite', code: 'MASTERCARD_WORLD_ELITE' },
    ],
  },
  {
    value: 'JCB',
    englishName: 'JCB',
    levels: [
      { value: '普卡', englishName: 'Classic', code: 'JCB_CLASSIC' },
      { value: '金卡', englishName: 'Gold', code: 'JCB_GOLD' },
      { value: '白金卡', englishName: 'Platinum', code: 'JCB_PLATINUM' },
      { value: '御尊卡', englishName: 'Prestige', code: 'JCB_PRESTIGE' },
    ],
  },
  {
    value: '美国运通',
    englishName: 'American Express',
    levels: [
      { value: '绿卡', englishName: 'Green', code: 'AMEX_GREEN' },
      { value: '金卡', englishName: 'Gold', code: 'AMEX_GOLD' },
      { value: '白金卡', englishName: 'Platinum', code: 'AMEX_PLATINUM' },
      { value: '黑金卡', englishName: 'Centurion', code: 'AMEX_CENTURION' },
    ],
  },
]

export const cardLevelData = cardLevelGroups.flatMap(group =>
  group.levels.map(level => {
    const value = `${group.value}-${level.value}`
    return {
      value,
      englishName: `${group.englishName} ${level.englishName}`,
      chineseName: value,
      code: level.code,
      aliases: [],
    }
  })
)

export const normalizeCardLevel = (value) => {
  const cleaned = String(value || '').trim()
  if (!cleaned) return ''
  if (cardLevelData.some(item => item.value === cleaned)) return cleaned
  if (cleaned.startsWith('MasterCard-') || cleaned.startsWith('Mastercard-')) {
    return cleaned.replace(/^Master[Cc]ard-/, '万事达-')
  }
  if (cleaned.startsWith('VISA-')) {
    return cleaned.replace(/^VISA-/, 'Visa-')
  }
  const legacyAmericanExpressLevels = {
    'AE-经典-绿卡': '美国运通-绿卡',
    'AE-经典-金卡': '美国运通-金卡',
    'AE-经典-新贵白金卡': '美国运通-白金卡',
    'AE-经典-百夫长白金卡': '美国运通-白金卡',
    'AE-经典-百夫长黑金卡': '美国运通-黑金卡',
  }
  return legacyAmericanExpressLevels[cleaned] || cleaned
}

export const currencyData = [
  { value: 'CNY', englishName: 'Chinese Yuan', chineseName: '人民币', code: 'CNY', symbol: '¥', aliases: ['rmb', 'renminbi'] },
  { value: 'CNH', englishName: 'Chinese Yuan Offshore', chineseName: '人民币离岸', code: 'CNH', symbol: 'CNH', aliases: [] },
  { value: 'USD', englishName: 'US Dollar', chineseName: '美元', code: 'USD', symbol: '$', aliases: ['usdollar'] },
  { value: 'EUR', englishName: 'Euro', chineseName: '欧元', code: 'EUR', symbol: '€', aliases: [] },
  { value: 'GBP', englishName: 'British Pound', chineseName: '英镑', code: 'GBP', symbol: '£', aliases: [] },
  { value: 'JPY', englishName: 'Japanese Yen', chineseName: '日元', code: 'JPY', symbol: '¥', aliases: [] },
  { value: 'HKD', englishName: 'Hong Kong Dollar', chineseName: '港币', code: 'HKD', symbol: 'HK$', aliases: [] },
  { value: 'MOP', englishName: 'Macanese Pataca', chineseName: '澳门币', code: 'MOP', symbol: 'MOP$', aliases: [] },
  { value: 'TWD', englishName: 'New Taiwan Dollar', chineseName: '新台币', code: 'TWD', symbol: 'NT$', aliases: [] },
  { value: 'SGD', englishName: 'Singapore Dollar', chineseName: '新加坡元', code: 'SGD', symbol: 'S$', aliases: [] },
  { value: 'AUD', englishName: 'Australian Dollar', chineseName: '澳元', code: 'AUD', symbol: 'A$', aliases: [] },
  { value: 'CAD', englishName: 'Canadian Dollar', chineseName: '加元', code: 'CAD', symbol: 'C$', aliases: [] },
  { value: 'CHF', englishName: 'Swiss Franc', chineseName: '瑞士法郎', code: 'CHF', symbol: 'CHF', aliases: [] },
  { value: 'SEK', englishName: 'Swedish Krona', chineseName: '瑞典克朗', code: 'SEK', symbol: 'SEK', aliases: [] },
  { value: 'DKK', englishName: 'Danish Krone', chineseName: '丹麦克朗', code: 'DKK', symbol: 'DKK', aliases: [] },
  { value: 'NOK', englishName: 'Norwegian Krone', chineseName: '挪威克朗', code: 'NOK', symbol: 'NOK', aliases: [] },
  { value: 'NZD', englishName: 'New Zealand Dollar', chineseName: '新西兰元', code: 'NZD', symbol: 'NZ$', aliases: [] },
  { value: 'KRW', englishName: 'Korean Won', chineseName: '韩元', code: 'KRW', symbol: 'KRW', aliases: [] },
  { value: 'THB', englishName: 'Thai Baht', chineseName: '泰铢', code: 'THB', symbol: '฿', aliases: [] },
  { value: 'MYR', englishName: 'Malaysian Ringgit', chineseName: '马来西亚林吉特', code: 'MYR', symbol: 'MYR', aliases: [] },
  { value: 'IDR', englishName: 'Indonesian Rupiah', chineseName: '印尼卢比', code: 'IDR', symbol: 'IDR', aliases: ['indonesian rupiah'] },
  { value: 'VND', englishName: 'Vietnamese Dong', chineseName: '越南盾', code: 'VND', symbol: 'VND', aliases: [] },
  { value: 'PHP', englishName: 'Philippine Peso', chineseName: '菲律宾比索', code: 'PHP', symbol: 'PHP', aliases: [] },
  { value: 'INR', englishName: 'Indian Rupee', chineseName: '印度卢比', code: 'INR', symbol: 'INR', aliases: [] },
]

export const qualificationStatusData = [
  { value: '1', englishName: 'Qualified', chineseName: '已达标', code: 'QUALIFIED', aliases: [] },
  { value: '2', englishName: 'Not Qualified', chineseName: '未达标', code: 'NOT_QUALIFIED', aliases: [] },
  { value: '3', englishName: 'Lifetime Fee Waived', chineseName: '终免年费', code: 'LIFETIME_WAIVED', aliases: ['fee waived forever'] },
]
